### ISSUE TITLE
Docker 启动后，小米登录验证失败

### ISSUE THREAD

**Issue by akring** [idootop/mi-gpt#10]
查看 log 后输出如下：
```
{
    "qs": "%3Fsid%3Dmicoapi%26_json%3Dtrue%26_locale%3Dzh_CN",
    "code": 70016,
    "description": "登录验证失败",
    "securityStatus": 0,
    "_sign": "3hTMVA4oMVVESndNZC0Uemsp6u8=",
    "sid": "micoapi",
    "result": "error",
    "captchaUrl": null,
    "callback": "https://api2.mina.mi.com/sts",
    "location": "",
    "pwd": 0,
    "child": 0,
    "desc": "登录验证失败"
}
```

**Comment by idootop** [comment]
首先确保你的账号密码信息正确，然后检查你的网络环境是否在中国境内。
部分异常网络环境下也可能会导致登录失败，参考 https://github.com/idootop/mi-gpt/issues/1  你的问题更像是账号密码错误。

**Comment by akring** [comment]
感谢回复，感觉更像是小米账号登录抽风了，刚才试了一下直接小米官网都不能正常登录了，一直在循环重定向（2 小时之前正常）。
明天我再试一下看看。

**Comment by akring** [comment]
经过多次测试，包括使用 mi-service-lite 之后，我发现我的情况确实是和 #1 相似，也是 401 错误。

`https://api2.mina.mi.com/admin/v2/device_list?requestId=48f48e34-593b-43bb-a710-aa9558a949b7&timestamp=1716986981`

同时我也尝试了切换网络环境，包括使用手机热点等方式，结果依然还是 401。

**Comment by akring** [comment]
最终发现问题所在，非常低级的个人错误：

小米账号不是邮箱或者手机号，而是登录之后「个人信息」里的「小米ID」

**Comment by haojun0001** [comment]
我也是相同的问题，解决了。感谢。

**Comment by luyunfeng** [comment]
这个密码是哪里的密码，是小米账户的密码吗

**Comment by idootop** [comment]
@luyunfeng 对的

**Comment by julihouca189** [comment]
获取 Mi Service Token 失败 {
  isError: true,
  code: 'ECONNABORTED',
  message: 'timeout of 5000ms exceeded',
2025/01/12 00:33:53 Speaker ❌ 初始化 Mi Services 失败
2025/01/12 00:33:53 database ❌  Error: ❌ Assertion failed
    at _LoggerManager.assert (C:\Projects\WayToAGI_AI\mi-gpt\dist\index.cjs:282:13)
    at __Logger.assert (C:\Projects\WayToAGI_AI\mi-gpt\dist\index.cjs:319:19)
    at AISpeaker.initMiServices (C:\Projects\WayToAGI_AI\mi-gpt\dist\index.cjs:499:17)
    at async AISpeaker.run (C:\Projects\WayToAGI_AI\mi-gpt\dist\index.cjs:771:5)
    at async main (file:///C:/Projects/WayToAGI_AI/mi-gpt/app.js:6:3)
 ELIFECYCLE  Command failed with exit code 1.

**Comment by linfengpeng** [comment]
用的小米账号ID 还是启动提示认证失败

**Comment by linfengpeng** [comment]
米账号登录失败 &&&START&&&{"qs":"%3Fsid%3Dmicoapi%26_json%3Dtrue%26_locale%3Dzh_CN","code":70016,"description":"登录验证失败","securityStatus":0,"_sign":"3hTMVA4oMVVESndNZC0Uemsp6u8=","sid":"micoapi","result":"error","captchaUrl":null,"callback":"https://api2.mina.mi.com/sts","location":"","pwd":0,"child":0,"desc":"登录验证失败"}
❌ 小米账号登录失败 &&&START&&&{"qs":"%3Fsid%3Dxiaomiio%26_json%3Dtrue%26_locale%3Dzh_CN","code":70016,"description":"登录验证失败","securityStatus":0,"_sign":"azrnTMZJiyQ9FtUVXA7ZD76KZYM=","sid":"xiaomiio","result":"error","captchaUrl":null,"callback":"https://sts.api.io.mi.com/sts","location":"","pwd":0,"child":0,"desc":"登录验证失败"}
2025/02/24 14:27:54 Speaker ❌ 初始化 Mi Services 失败
2025/02/24 14:27:54 database ❌  Error: ❌ Assertion failed
    at _LoggerManager.assert (/Users/linfengpeng/Documents/CodeWork/MI-GDP/mi-gpt/dist/index.cjs:279:13)
    at __Logger.assert (/Users/linfengpeng/Documents/CodeWork/MI-GDP/mi-gpt/dist/index.cjs:316:19)
    at AISpeaker.initMiServices (/Users/linfengpeng/Documents/CodeWork/MI-GDP/mi-gpt/dist/index.cjs:496:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async AISpeaker.run (/Users/linfengpeng/Documents/CodeWork/MI-GDP/mi-gpt/dist/index.cjs:768:5)
    at async main (file:///Users/linfengpeng/Documents/CodeWork/MI-GDP/mi-gpt/app.js:6:3)
linfengpeng@Mac mi-gpt %

**Comment by zactang** [comment]
2025-03-04 15:19:37 ❌ 登录失败 {
2025-03-04 15:19:37   isError: true,
2025-03-04 15:19:37   code: 'ECONNABORTED',
2025-03-04 15:19:37   message: 'timeout of 5000ms exceeded',

**Comment by kaermeixi** [comment]
🔥 触发小米账号异地登录安全验证机制，请在浏览器打开以下链接，并按照网页提示授权验证账号：
2025-04-09 08:47:11 👉 https://account.xiaomi.com/identity/authStart?sid=xiaomiio&context=GCXZIwZiOV4sTxJmXce-sQbGCKGDo52BJhExTEZBC50H1Dzg-GEs9zMJpCntBrSmtQZsxMbn5rRRfS-0XXPFp4fyNZ5xExvZ_8KHqoKkEcCa86PnzzvikG_TVcFOWPkbd_0hIFInIcJSdzi2MeDrAhNgmRxyzATnBvu9-eTnwhGItn6xQt9kFgm8L_lUNPY0JP20GGA_MKQcVRQwF-V0Mw0sCam5PaKuyJWNNw6aTXPeeLucHVcu0Bgcz87t7Df7izjUfrmGuQvSps2QnJsfqZKAd3oSovl0DD2ZZeD7NVYpl__IJPBHKF00XUJXiAHa0ozlw8etuDma7j5i0JbiPsRIdkOIum0ogKxdWV-a1w7N03TRHW7aTcZxwMuwMefK9cflRfdSjfir4qVuy6Uy4wRxoupOk8DeS6qfIICstrlMOLPN7QYgZ2Q1wOQVViWk3hbtDs6vsoHBsZ9KH09aGM0e4khMZKEEbRkdnThJlakrotPPpPNCOAqh1FigCB7A6A8E2YtmdF2r5TRtgRFumRuqqNA-ON3nQzKHJ9zBVUN5iCwI37nHDI2psEUKFf6-11CQoLLCNvuEzCj5frBC2IyUviBJD6GtErQaPNUVGNhy7WVSohMFWsqAwMYoOUB33NI1ZHU9Nh-G0WQWUn2xEO2hyrYKH9_iFsyF1Wq3gPA&_locale=zh_CN
2025-04-09 08:47:11 🐛 注意：授权成功后，大约需要等待 1 个小时左右账号信息才会更新，请在更新后再尝试重新登录。
2025-04-09 08:47:11 ❌ 找不到设备：小米Ai音箱
2025-04-09 08:47:11 ❌ 小米账号登录失败 &&&START&&&{"notificationUrl":"https://account.xiaomi.com/identity/authStart?sid=xiaomiio&context=GCXZIwZiOV4sTxJmXce-sQbGCKGDo52BJhExTEZBC50H1Dzg-GEs9zMJpCntBrSmtQZsxMbn5rRRfS-0XXPFp4fyNZ5xExvZ_8KHqoKkEcCa86PnzzvikG_TVcFOWPkbd_0hIFInIcJSdzi2MeDrAhNgmRxyzATnBvu9-eTnwhGItn6xQt9kFgm8L_lUNPY0JP20GGA_MKQcVRQwF-V0Mw0sCam5PaKuyJWNNw6aTXPeeLucHVcu0Bgcz87t7Df7izjUfrmGuQvSps2QnJsfqZKAd3oSovl0DD2ZZeD7NVYpl__IJPBHKF00XUJXiAHa0ozlw8etuDma7j5i0JbiPsRIdkOIum0ogKxdWV-a1w7N03TRHW7aTcZxwMuwMefK9cflRfdSjfir4qVuy6Uy4wRxoupOk8DeS6qfIICstrlMOLPN7QYgZ2Q1wOQVViWk3hbtDs6vsoHBsZ9KH09aGM0e4khMZKEEbRkdnThJlakrotPPpPNCOAqh1FigCB7A6A8E2YtmdF2r5TRtgRFumRuqqNA-ON3nQzKHJ9zBVUN5iCwI37nHDI2psEUKFf6-11CQoLLCNvuEzCj5frBC2IyUviBJD6GtErQaPNUVGNhy7WVSohMFWsqAwMYoOUB33NI1ZHU9Nh-G0WQWUn2xEO2hyrYKH9_iFsyF1Wq3gPA&_locale=zh_CN","result":"ok","code":0,"captchaUrl":null,"description":"成功","location":"","securityStatus":16,"pwd":0,"child":0,"desc":"成功"}
2025-04-09 08:47:11 2025/04/09 00:47:11 Speaker ❌ 初始化 Mi Services 失败
2025-04-09 08:47:11 2025/04/09 00:47:11 database ❌  Error: ❌ Assertion failed
2025-04-09 08:47:11     at _LoggerManager.assert (file:///usr/local/lib/node_modules/migpt-server/node_modules/mi-gpt/dist/index.js:270:13)
2025-04-09 08:47:11     at __Logger.assert (file:///usr/local/lib/node_modules/migpt-server/node_modules/mi-gpt/dist/index.js:307:19)
2025-04-09 08:47:11     at AISpeaker.initMiServices (file:///usr/local/lib/node_modules/migpt-server/node_modules/mi-gpt/dist/index.js:487:17)
2025-04-09 08:47:11     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-04-09 08:47:11     at async AISpeaker.run (file:///usr/local/lib/node_modules/migpt-server/node_modules/mi-gpt/dist/index.js:759:5)
2025-04-09 08:47:53 node:events:497
2025-04-09 08:47:53       throw er; // Unhandled 'error' event
2025-04-09 08:47:53       ^
2025-04-09 08:47:53 
2025-04-09 08:47:53 Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
2025-04-09 08:47:53     at target.send (node:internal/child_process:754:16)
2025-04-09 08:47:53     at file:///usr/local/lib/node_modules/migpt-server/node_modules/@migptgui/controller/dist/index.js:11:19
2025-04-09 08:47:53     at new Promise (<anonymous>)
2025-04-09 08:47:53     at killChild (file:///usr/local/lib/node_modules/migpt-server/node_modules/@migptgui/controller/dist/index.js:6:12)
2025-04-09 08:47:53     at run (file:///usr/local/lib/node_modules/migpt-server/node_modules/@migptgui/controller/dist/index.js:23:11)
2025-04-09 08:47:53     at file:///usr/local/lib/node_modules/migpt-server/node_modules/@migptgui/server/dist/index.js:270:15
2025-04-09 08:47:53 Emitted 'error' event on ChildProcess instance at:
2025-04-09 08:47:53     at node:internal/child_process:758:35
2025-04-09 08:47:53     at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
2025-04-09 08:47:53   code: 'ERR_IPC_CHANNEL_CLOSED'
2025-04-09 08:47:53 }
2025-04-09 08:47:53 
2025-04-09 08:47:53 Node.js v20.15.0
2025-04-09 08:48:15 端口： 36592
2025-04-09 08:48:15 登录认证： 未启用
2025-04-09 08:48:15 秘密路径： 已启用

**Comment by lzh2059** [comment]
<html>
<body>

2025/10/25 09:52:34 | stdout | 秘密路径： 已启用
-- | -- | --
2025/10/25 09:52:34 | stdout | 登录认证： 未启用
2025/10/25 09:52:34 | stdout | 端口： 36592
2025/10/25 09:52:02 | stderr | Node.js v20.15.0
2025/10/25 09:52:02 | stderr |  
2025/10/25 09:52:02 | stderr | }
2025/10/25 09:52:02 | stderr | code: 'ERR_IPC_CHANNEL_CLOSED'
2025/10/25 09:52:02 | stderr | at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
2025/10/25 09:52:02 | stderr | at node:internal/child_process:758:35
2025/10/25 09:52:02 | stderr | Emitted 'error' event on ChildProcess instance at:
2025/10/25 09:52:02 | stderr | at file:///usr/local/lib/node_modules/migpt-server/node_modules/@migptgui/server/dist/index.js:270:15
2025/10/25 09:52:02 | stderr | at run (file:///usr/local/lib/node_modules/migpt-server/node_modules/@migptgui/controller/dist/index.js:23:11)
2025/10/25 09:52:02 | stderr | at killChild (file:///usr/local/lib/node_modules/migpt-server/node_modules/@migptgui/controller/dist/index.js:6:12)
2025/10/25 09:52:02 | stderr | at new Promise (<anonymous>)
2025/10/25 09:52:02 | stderr | at file:///usr/local/lib/node_modules/migpt-server/node_modules/@migptgui/controller/dist/index.js:11:19
2025/10/25 09:52:02 | stderr | at target.send (node:internal/child_process:754:16)
2025/10/25 09:52:02 | stderr | Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
2025/10/25 09:52:02 | stderr |  
2025/10/25 09:52:02 | stderr | ^
2025/10/25 09:52:02 | stderr | throw er; // Unhandled 'error' event
2025/10/25 09:52:02 | stderr | node:events:497
2025/10/25 09:49:08 | stderr | at async AISpeaker.run (file:///usr/local/lib/node_modules/migpt-server/node_modules/mi-gpt/dist/index.js:759:5)
2025/10/25 09:49:08 | stderr | at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2025/10/25 09:49:08 | stderr | at AISpeaker.initMiServices (file:///usr/local/lib/node_modules/migpt-server/node_modules/mi-gpt/dist/index.js:487:17)
2025/10/25 09:49:08 | stderr | at __Logger.assert (file:///usr/local/lib/node_modules/migpt-server/node_modules/mi-gpt/dist/index.js:307:19)
2025/10/25 09:49:08 | stderr | at _LoggerManager.assert (file:///usr/local/lib/node_modules/migpt-server/node_modules/mi-gpt/dist/index.js:270:13)
2025/10/25 09:49:08 | stderr | 2025/10/25 01:49:08 database ❌  Error: ❌ Assertion failed
2025/10/25 09:49:08 | stderr | 2025/10/25 01:49:08 Speaker ❌ 初始化 Mi Services 失败
2025/10/25 09:49:08 | stderr | ❌ 小米账号登录失败 &&&START&&&{"notificationUrl":"https://account.xiaomi.com/fe/service/identity/authStart?sid=xiaomiio&context=H6dc3UigtYd5hLJpQvh4Sz6m9-6OuS3MXOCTez87-BbsooKmhAxaQChdPU79hKrEIdr--QsvDh36wOJyfhcO-3Mv2hx1Swh3BMM2Nz7-FYM-yqA2QgLHHs648I1A737he3dMf4BO528N989_0dBUMT7bC1K4z4C4XVnR7Edbs7y9gq1t9MGZCK5zTBalKaq2YD-mOJLPxasDugovcsXmJ0BEeY4gYPTqVzCnotR51-lNrTklJ0e0LQXivk5HGIio-opJrXw9cF9fAziPG5u9JBsttV-hwKyft2zN44FCtNkNWs8YSWKRJ2pMLrR0SYxonMxqpv9BiEDjCiNnw1jYy0HmWOoW2ZQpjuLYERyrx-bNKzjA09TibVgdRj7gmcVz1B3hd_1G8xl6gFXkguP9Sbw4nOSgKSNpWhu2Xu_RVCoDbLZa3rbauO9wiHOwh3LswEimAOYvYSa7eHB2GMmtaVtpstHDvTv_jtvf-5G8ckEQtZOZD2UjUMwlHPsUKfGHj3R3At72_koO6DZLwUcgzqHFjn1V6DZPcPPghbCjWlpPRFbrwDnPKN9GrSutoW6C5nHBNJ8xlG_elDKai8jRDQZjDmPFVU5xHkFAhSrR34SPNntw3gREFrcEznlVM8Mgg5LowaViFDMTnKan1vJEXA&_locale=zh_CN","result":"ok","code":0,"miDemo":0,"captchaUrl":null,"description":"成功","location":"","securityStatus":16,"pwd":0,"child":0,"desc":"成功"}
2025/10/25 09:49:08 | stdout | 🐛 注意：授权成功后，大约需要等待 1 个小时左右账号信息才会更新，请在更新后再尝试重新登录。
2025/10/25 09:49:08 | stdout | 👉 https://account.xiaomi.com/fe/service/identity/authStart?sid=xiaomiio&context=H6dc3UigtYd5hLJpQvh4Sz6m9-6OuS3MXOCTez87-BbsooKmhAxaQChdPU79hKrEIdr--QsvDh36wOJyfhcO-3Mv2hx1Swh3BMM2Nz7-FYM-yqA2QgLHHs648I1A737he3dMf4BO528N989_0dBUMT7bC1K4z4C4XVnR7Edbs7y9gq1t9MGZCK5zTBalKaq2YD-mOJLPxasDugovcsXmJ0BEeY4gYPTqVzCnotR51-lNrTklJ0e0LQXivk5HGIio-opJrXw9cF9fAziPG5u9JBsttV-hwKyft2zN44FCtNkNWs8YSWKRJ2pMLrR0SYxonMxqpv9BiEDjCiNnw1jYy0HmWOoW2ZQpjuLYERyrx-bNKzjA09TibVgdRj7gmcVz1B3hd_1G8xl6gFXkguP9Sbw4nOSgKSNpWhu2Xu_RVCoDbLZa3rbauO9wiHOwh3LswEimAOYvYSa7eHB2GMmtaVtpstHDvTv_jtvf-5G8ckEQtZOZD2UjUMwlHPsUKfGHj3R3At72_koO6DZLwUcgzqHFjn1V6DZPcPPghbCjWlpPRFbrwDnPKN9GrSutoW6C5nHBNJ8xlG_elDKai8jRDQZjDmPFVU5xHkFAhSrR34SPNntw3gREFrcEznlVM8Mgg5LowaViFDMTnKan1vJEXA&_locale=zh_CN
2025/10/25 09:49:08 | stdout | 🔥 触发小米账号异地登录安全验证机制，请在浏览器打开以下链接，并按照网页提示授权验证账号：
2025/10/25 09:49:05 | stdout |  
2025/10/25 09:49:05 | stdout |  
2025/10/25 09:49:05 | stdout | MiGPT v4.2.0  by: del.wang
2025/10/25 09:49:05 | stdout |  
2025/10/25 09:49:05 | stdout | \|__/     \|__/\|__/ \______/ \|__/         \|__/
2025/10/25 09:49:05 | stdout | \| $$ \/  \| $$\| $$\|  $$$$$$/\| $$         \| $$
2025/10/25 09:49:05 | stdout | \| $$\  $ \| $$\| $$\| $$  \ $$\| $$         \| $$
2025/10/25 09:49:05 | stdout | \| $$  $$$\| $$\| $$\| $$\|_  $$\| $$____/    \| $$
2025/10/25 09:49:05 | stdout | \| $$ $$/$$ $$\| $$\| $$ /$$$$\| $$$$$$$/   \| $$
2025/10/25 09:49:05 | stdout | \| $$$$  /$$$$ /$$\| $$  \__/\| $$  \ $$   \| $$
2025/10/25 09:49:05 | stdout | \| $$$    /$$$\|__/ /$$__  $$\| $$__  $$\|__  $$__/
2025/10/25 09:49:05 | stdout | / $$      /$$ /$$   /$$$$$$  /$$$$$$$ /$$$$$$$$$


</body>
</html>

**Comment by seryte** [comment]
mark一下
