### ISSUE TITLE
windows平台，使用nodejs运行，出现如下错误

### ISSUE THREAD

**Issue by haojun0001** [idootop/mi-gpt#12]
你好，我尝试在windows平台，使用nodejs运行，出现如下错误:
Node.js v20.14.0

E:\1.Code\NodeJsWorkspace\mi-gpt>pnpm install && pnpm build               
Lockfile is up to date, resolution step is skipped
Packages: +175
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 175, reused 175, downloaded 0, added 175, done

dependencies:
+ @prisma/client 5.14.0  
+ axios 1.6.8
+ fs-extra 11.2.0        
+ https-proxy-agent 7.0.4
+ mi-gpt 2.0.0
+ mi-service-lite 2.3.0  
+ openai 4.47.1
+ prisma 5.14.0

devDependencies:
+ @types/fs-extra 11.0.4 
+ @types/node 20.12.12   
+ dotenv 16.4.5
+ ts-node 10.9.2
+ tsup 8.0.2
+ typescript 5.4.5       

Done in 2.7s

> mi-gpt@2.0.0 build E:\1.Code\NodeJsWorkspace\mi-gpt
> pnpm prisma generate && tsup

Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma

✔ Generated Prisma Client (v5.14.0) to .\node_modules\.pnpm\@prisma+client@5.14.0_prisma@5.14.0\node_modules\@prisma\client in 163ms

Start using Prisma Client in Node.js (See: https://pris.ly/d/client)
```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```
or start using Prisma Client at the edge (See: https://pris.ly/d/accelerate)
```
import { PrismaClient } from '@prisma/client/edge'
const prisma = new PrismaClient()
```

See other ways of importing Prisma Client: http://pris.ly/d/importing-client

┌─────────────────────────────────────────────────────────────┐
│  Deploying your app to serverless or edge functions?        │
│  Try Prisma Accelerate for connection pooling and caching.  │
│  https://pris.ly/cli/--accelerate                           │
└─────────────────────────────────────────────────────────────┘

CLI Building entry: src/index.ts
CLI Using tsconfig: tsconfig.json
CLI tsup v8.0.2
CLI Using tsup config: E:\1.Code\NodeJsWorkspace\mi-gpt\tsup.config.ts
CLI Target: node16
CLI Cleaning output folder
ESM Build start
CJS Build start
CJS dist\index.cjs 75.69 KB
CJS ⚡️ Build success in 462ms
ESM dist\index.js 75.08 KB
ESM ⚡️ Build success in 464ms
DTS Build start
DTS ⚡️ Build success in 3088ms
DTS dist\index.d.ts  12.86 KB
DTS dist\index.d.cts 12.86 KB

E:\1.Code\NodeJsWorkspace\mi-gpt>npm run start

> mi-gpt@2.0.0 start
> node ./scripts/runner.js

2024/05/29 20:32:00 MiGPT ❌ Missing userId or password.
E:\1.Code\NodeJsWorkspace\mi-gpt\dist\index.cjs:281
      throw Error("\u274C Assertion failed");
            ^

Error: ❌ Assertion failed
    at _LoggerManager.assert (E:\1.Code\NodeJsWorkspace\mi-gpt\dist\index.cjs:281:13)
    at __Logger.assert (E:\1.Code\NodeJsWorkspace\mi-gpt\dist\index.cjs:313:19)
    at _MiGPT.create (E:\1.Code\NodeJsWorkspace\mi-gpt\dist\index.cjs:2321:19)
    at main (file:///E:/1.Code/NodeJsWorkspace/mi-gpt/scripts/runner.js:5:24)
    at file:///E:/1.Code/NodeJsWorkspace/mi-gpt/scripts/runner.js:9:1
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5)

**Comment by haojun0001** [comment]
![Uploading 1.png…]()

**Comment by haojun0001** [comment]
![1](https://github.com/idootop/mi-gpt/assets/20295453/d53e8221-3496-426e-a8a9-013d54226835)

**Comment by haojun0001** [comment]
![图片](https://github.com/idootop/mi-gpt/assets/20295453/e5bd2ad7-fe4d-419d-9dcb-9405dbc668e9)

**Comment by haojun0001** [comment]
![图片](https://github.com/idootop/mi-gpt/assets/20295453/f7d170f7-81f8-47c9-a1c3-010861143414)
修改代码后出现如下错误信息：
E:\1.Code\NodeJsWorkspace\mi-gpt>npm run start

> mi-gpt@2.0.0 start
> node ./scripts/runner.js

node:events:497
      throw er; // Unhandled 'error' event
      ^

Error: spawn npx ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:292:12)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn npx',
  path: 'npx',
  spawnargs: [
    'prisma',
    'migrate',
    'dev',
    '--name',
    'init',
    '--schema',
    'node_modules/mi-gpt/prisma/schema.prisma'
  ]
}

**Comment by haojun0001** [comment]
npm install -g prisma
prisma migrate dev --name init --schema node_modules/mi-gpt/prisma/schema.prisma
解决问题
