### ISSUE TITLE
feat: do not need use command

### ISSUE THREAD

**Issue by yihong0618** [idootop/mi-gpt#134]
可以参考 @hanxi 的这个 PR https://github.com/yihong0618/MiService/pull/33

**Comment by idootop** [comment]
感谢，稍后我测试下。

**Comment by hanxi** [comment]
有人反馈触屏版还是播放不了，我没设备调试。。。

**Comment by idootop** [comment]
@yihong0618 我看了下这个 PR 里的内容，对于播放音频链接提供了一个很好的思路，或许可以解决当前 mi-gpt 部分机型使用不了第三方 TTS 的问题（通过 play 接口下发播放 tts 音频链接的指令后，小爱音箱没有去请求对应的接口）。
@hanxi 这个 payload 和 type 的含义都能找出来，真厉害👍，哈哈。

**Comment by hanxi** [comment]
@idootop 抓包找的接口，接口参数没加密，目前测试了 L05B L05C 可以播放，LX04  X10A  X08A 不能播放，屏幕会弹出一个音乐节目，估计是参数有问题。你这里用户多，如果有人有设备且会在手机上抓包小爱音箱app的话可以帮忙抓包试试看。
我是用 https://reqable.com/zh-CN/ 抓包的，见 
https://github.com/hanxi/xiaomusic/issues/49

**Comment by idootop** [comment]
@hanxi  嗯，我在另一个老哥逆向出的安卓米家源码里找到相关 model 的定义了：[PlayListSong](https://github.com/argahsuknesib/CyberSecurity-Summer-School-2021/blob/39cbcbe3c59f241cebf36c2acd65fff202849b22/RiskInDroid/AndroidApp/xiaomi/sources/com/xiaomi/mico/api/model/PlayV3Pact.java#L125)

从[逆向出来的源码](https://github.com/argahsuknesib/CyberSecurity-Summer-School-2021/blob/39cbcbe3c59f241cebf36c2acd65fff202849b22/RiskInDroid/AndroidApp/xiaomi/sources/com/xiaomi/mico/music/player/PlayerManager.java#L171) 看，应该是跟 Mico 使用的协议版本相关。

这个 payload 应该是给 v3 高版本协议用的，低版本应该是走的另一个 payload：

<img width="492" alt="图片" src="https://github.com/idootop/mi-gpt/assets/35302658/a6328f71-a632-4e9d-9db1-67395995334c">

可以看到低版本的 payload 里是无法自定义 song 的 url 的。

**Comment by yihong0618** [comment]
> @hanxi 嗯，我在另一个老哥逆向出的安卓米家源码里找到相关 model 的定义了：[PlayListSong](https://github.com/argahsuknesib/CyberSecurity-Summer-School-2021/blob/39cbcbe3c59f241cebf36c2acd65fff202849b22/RiskInDroid/AndroidApp/xiaomi/sources/com/xiaomi/mico/api/model/PlayV3Pact.java#L125)
> 
> 从[逆向出来的源码](https://github.com/argahsuknesib/CyberSecurity-Summer-School-2021/blob/39cbcbe3c59f241cebf36c2acd65fff202849b22/RiskInDroid/AndroidApp/xiaomi/sources/com/xiaomi/mico/music/player/PlayerManager.java#L171) 看，应该是跟 Mico 使用的协议版本相关。
> 
> 这个 payload 应该是给 v3 高版本协议用的，低版本应该是走的另一个 payload：
> 
> <img alt="图片" width="492" src="https://private-user-images.githubusercontent.com/35302658/343987480-a6328f71-a632-4e9d-9db1-67395995334c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1Mzg3NTUsIm5iZiI6MTcxOTUzODQ1NSwicGF0aCI6Ii8zNTMwMjY1OC8zNDM5ODc0ODAtYTYzMjhmNzEtYTYzMi00ZTlkLTlkYjEtNjczOTU5OTUzMzRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDAxMzQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkOTZiNjljZmM2MjExZWY4OGY2OGU0ODY4ZmNkYzI3NmViMzUwOTQ5ZjdkYTM5ZjRiYmU0YWZlN2FlZWM4YTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X94CQnllbNhKBzXtJxTCJQorR0biJZs73GK7w8mKWF0">
> 可以看到低版本的 payload 里是无法自定义 song 的 url 的。

有更好的方式也欢迎 PR.

**Comment by hanxi** [comment]
有朋友帮忙抓包测试了触屏版 X08C 也是用的 player_play_music 接口播放音乐的，估计是参数问题，或者音箱那边做了限制。

**Comment by idootop** [comment]
目测后者的可能性更大一些，相同的指令，有些型号就是不执行。
神奇的是有些时候返回的结果还是播放成功（可能只是指令下发成功，不验证是否开始正常播放）

**Comment by hanxi** [comment]
同步触屏版最新情况，已经有部分设备测试能播放音乐了，主要是补充几个关键的参数。相关提交见 
https://github.com/hanxi/xiaomusic/commit/e97639302f4a3ace48a6f300ef8acd99c15a519a

**Comment by xiajingjie** [comment]
> 感谢，稍后我测试下。
大佬，Debain自部署node.js，报错 The OPENAI_API_KEY environment variable  is missing or empty。已经设置了.env和.migpt.js。
过程如下：
npm start
> mi-gpt@4.1.0 start
> node ./app.js
/ $$      /$$ /$$   /$$$$$$  /$$$$$$$ /$$$$$$$$$
| $$$    /$$$|__/ /$$__  $$| $$__  $$|__  $$__/
| $$$$  /$$$$ /$$| $$  \__/| $$  \ $$   | $$
| $$ $$/$$ $$| $$| $$ /$$$$| $$$$$$$/   | $$
| $$  $$$| $$| $$| $$|_  $$| $$____/    | $$
| $$\  $ | $$| $$| $$  \ $$| $$         | $$
| $$ \/  | $$| $$|  $$$$$$/| $$         | $$
|__/     |__/|__/ \______/ |__/         |__/       
                                                                                                      
         MiGPT v4.1.0  by: del.wang
2024/07/08 18:22:51 Speaker ✅ 服务已启动...
2024/07/08 18:23:04 Speaker 🔥 召唤SIRI
2024/07/08 18:23:04 Speaker 🔊 你好，我是傻妞，很高兴认识你
2024/07/08 18:23:15 Speaker 🔥 明天多少度
2024/07/08 18:23:16 Speaker 🔊 请稍等
/opt/migpt/node_modules/openai/index.js:55
            throw new Errors.OpenAIError("The OPENAI_API_KEY environment variable is missing or empty; either provide it, or instantiate the OpenAI client with an apiKey option, like new OpenAI({ apiKey: 'My API Key' }).");
                  ^
OpenAIError: The OPENAI_API_KEY environment variable is missing or empty; either provide it, or instantiate the OpenAI client with an apiKey option, like new OpenAI({ apiKey: 'My API Key' }).
    at new OpenAI (/opt/migpt/node_modules/openai/index.js:55:19)
    at OpenAIClient._init (/opt/migpt/dist/index.cjs:1152:12)
    at OpenAIClient.chatStream (/opt/migpt/dist/index.cjs:1214:10)
    at _MyBot.chatWithStreamResponse (/opt/migpt/dist/index.cjs:2339:12)
    at _MyBot.ask (/opt/migpt/dist/index.cjs:2321:33)
    at async AISpeaker._askAIForAnswerSteps.res.response (/opt/migpt/dist/index.cjs:1061:20)
    at async AISpeaker.askAIForAnswer (/opt/migpt/dist/index.cjs:1096:19)
    at async AISpeaker.onMessage (/opt/migpt/dist/index.cjs:806:24)
Node.js v20.15.0

**Comment by idootop** [comment]
@xiajingjie 

1. 不要在当前 issue 下讨论无关话题（很不礼貌），有其他问题请提交新的 issue。
3. Node.js 本地运行教程，请自行阅读[本地开发](https://github.com/idootop/mi-gpt/blob/main/docs/development.md)文档

<img width="999" alt="图片" src="https://github.com/idootop/mi-gpt/assets/35302658/36082eb3-4aef-44c9-92f1-6419e8adf11f">

**Comment by idootop** [comment]
@yihong0618 @hanxi 前些日子把小爱音箱 Pro 的刷机给搞定了，最近在用 Rust 写拦截小爱音频流输入输出的补丁。

现在终于可以摆脱原来唯一的轮训 API 的方案了，届时 XiaoGPT 和 XiaoMusic 也可以更新一波。


![Image](https://github.com/user-attachments/assets/dcf9fdfd-3eb1-4bed-90a1-a2d30a2f2310)

![Image](https://github.com/user-attachments/assets/4ba61d9c-241b-46d2-bd0c-bf6754f70043)

补充一下细节：
1. 这个月刚发布的小爱音箱 Pro 新款无需拆机即可刷机，需要一根 typec 数据线和一台 x86_64 的 Windows 电脑
2. 旧款小爱音箱 Pro 也能刷，不过需要拆机 + 一根 mico-USB 的数据线（无需焊接 ttl 调试线）
3. 旧款小爱音箱 Pro 内存和可读写的持久化 /data 分区容量均为 10 mb 左右，新款为原来的 10 倍（100mb） 可以跑更多的应用
4. 目前已经完成了 
	a. 官方固件提取、开启 ssh 并固化、修改登录密码、添加自定义开机启动脚本
	b. server 端和 client 端的实时双向通信：
		i.  转发小爱音箱的麦克风输入音频流到 server
		iii. server 端调用 client 端执行任意脚本（静音、播放音乐、关闭重启小米服务等
		iv. 转发小爱音箱的事件到 server（语音识别结果、播放状态等

拿到小爱音箱的输入音频流之后，自定义唤醒词、ASR 之类的任务也成为可能，包括流式播放 TTS 音频流。

比如直接对接另一个小智 AI 项目的 server 端等等，扩展性和可玩性极高。
	
等后面 client 端的补丁程序开发稳定之后，有时间我会整理并开放出刷机相关的教程。

**Comment by yihong0618** [comment]
敬仰！

**Comment by idootop** [comment]
**更新**：刷机后的小爱音箱接入小智 AI 的验证已经通过了，效果还是可以的。

演示视频：https://www.bilibili.com/video/BV1NBXWYSEvX

近期我已经在整理相关代码和教程了，敬请期待。

**Comment by dsk1990** [comment]
> [@yihong0618](https://github.com/yihong0618) [@hanxi](https://github.com/hanxi) 前些日子把小爱音箱 Pro 的刷机给搞定了，最近在用 Rust 写拦截小爱音频流输入输出的补丁。
> 
> 现在终于可以摆脱原来唯一的轮训 API 的方案了，届时 XiaoGPT 和 XiaoMusic 也可以更新一波。
> 
> ![Image](https://github.com/user-attachments/assets/dcf9fdfd-3eb1-4bed-90a1-a2d30a2f2310)
> 
> ![Image](https://github.com/user-attachments/assets/4ba61d9c-241b-46d2-bd0c-bf6754f70043)
> 
> 补充一下细节：
> 
> 1. 这个月刚发布的小爱音箱 Pro 新款无需拆机即可刷机，需要一根 typec 数据线和一台 x86_64 的 Windows 电脑
> 2. 旧款小爱音箱 Pro 也能刷，不过需要拆机 + 一根 mico-USB 的数据线（无需焊接 ttl 调试线）
> 3. 旧款小爱音箱 Pro 内存和可读写的持久化 /data 分区容量均为 10 mb 左右，新款为原来的 10 倍（100mb） 可以跑更多的应用
> 4. 目前已经完成了
>    a. 官方固件提取、开启 ssh 并固化、修改登录密码、添加自定义开机启动脚本
>    b. server 端和 client 端的实时双向通信：
>    i.  转发小爱音箱的麦克风输入音频流到 server
>    iii. server 端调用 client 端执行任意脚本（静音、播放音乐、关闭重启小米服务等
>    iv. 转发小爱音箱的事件到 server（语音识别结果、播放状态等
> 
> 拿到小爱音箱的输入音频流之后，自定义唤醒词、ASR 之类的任务也成为可能，包括流式播放 TTS 音频流。
> 
> 比如直接对接另一个小智 AI 项目的 server 端等等，扩展性和可玩性极高。
> 
> 等后面 client 端的补丁程序开发稳定之后，有时间我会整理并开放出刷机相关的教程。

补充一下：2025.02.27新发布的布艺、type-c电源线音箱产品名字叫“小米智能音箱pro”（非小爱音箱 Pro）。
项目主b站最新视频小智项目按键对话效果非常流畅，不知道语音交互能做到什么水平，期待❤
另近日该款京东/天猫有220~230的好价（smzdm），我先把设备准备起来😄

**Comment by dsk1990** [comment]
> **更新**：刷机后的小爱音箱接入小智 AI 的验证已经通过了，效果还是可以的。
> 
> 演示视频：https://www.bilibili.com/video/BV1NBXWYSEvX演示视频：https://www.bilibili.com/video/BV1NBXWYSEvX
> 
> 近期我已经在整理相关代码和教程了，敬请期待。
补充一下：2025.2.27最新发布的布艺/type-c款音箱官方名字叫“小米智能音箱pro”，非“小爱音箱 Pro”。
以上B站视频效果非常流畅，不知道语音交互能到什么效果，非常期待❤
另外新款近日京东/天猫有220~230好价（smzdm），我先把设备准备好😄

**Comment by zhangjinling** [comment]
我的是老款小爱音箱pro，到时候看看效果。
