### ISSUE TITLE
使用了kimi，设置了baseurl，但还是报错

### ISSUE THREAD

**Issue by csjuXYZ** [idootop/mi-gpt#18]
## kimi 配置
OPENAI_BASE_URL=https://api.moonshot.cn/v1
OPENAI_MODEL=moonshot-v1-8k
OPENAI_API_KEY=sk-TuKL1mvY**************lCirQ67YG9o7WRtpIvx9

## 报错信息
2024/06/02 23:31:52 Open AI ❌ ❌ openai chat failed AuthenticationError: 401 Invalid Authentication
    at APIError.generate (D:\document\Github\mi-gpt\node_modules\.pnpm\openai@4.47.3\node_modules\openai\error.js:48:20)
    at OpenAI.makeStatusError (D:\document\Github\mi-gpt\node_modules\.pnpm\openai@4.47.3\node_modules\openai\core.js:263:33)
    at OpenAI.makeRequest (D:\document\Github\mi-gpt\node_modules\.pnpm\openai@4.47.3\node_modules\openai\core.js:306:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async OpenAIClient.chatStream (D:\document\Github\mi-gpt\dist\index.cjs:1140:20) {
  status: 401,
  headers: {
    connection: 'keep-alive',
    'content-length': '84',
    'content-type': 'application/json; charset=utf-8',
    date: 'Sun, 02 Jun 2024 15:31:52 GMT',
    'msh-cache': 'miss',
    server: 'nginx',
    'server-timing': 'inner; dur=59',
    'strict-transport-security': 'max-age=15724800; includeSubDomains',
    vary: 'Origin'
  },
  request_id: undefined,
  error: {
    message: 'Invalid Authentication',
    type: 'invalid_authentication_error'
  },
  code: undefined,
  param: undefined,
  type: 'invalid_authentication_error'
}

**Comment by idootop** [comment]
检查你的 env 是否生效，我刚注册了 Moonshot 试了下，可以正常使用：
<img width="802" alt="图片" src="https://github.com/idootop/mi-gpt/assets/35302658/72d45b47-56df-4806-9442-09b3c58a942b">

**Comment by idootop** [comment]
未复现，请检查你的 API_KEY 是否可用。

**Comment by csjuXYZ** [comment]
> 未复现，请检查你的 API_KEY 是否可用。

刚用对话工具测试过key，是可用的，但是在node方式里，通过和小爱音箱的对话的方式使用会报错
我尝试过切换不同的服务，得到的鉴权失败信息有所不同，这说明是未能正确传递api_key

以下是我的月之暗面配置，
OPENAI_BASE_URL=https://api.moonshot.cn/v1
OPENAI_MODEL=moonshot-v1-8k
OPENAI_API_KEY=sk-TuKL1mvY2QXN8foNu0QSzL2Oa0pnlCirQ67YG9o7WRtpIvx9



2024/06/03 09:37:19 Open AI ❌ ❌ openai chat failed AuthenticationError: 401 Incorrect API key provided
    at APIError.generate (file:///D:/document/Github/mi-gpt-2/node_modules/.pnpm/openai@4.47.3/node_modules/openai/error.mjs:44:20)
    at OpenAI.makeStatusError (file:///D:/document/Github/mi-gpt-2/node_modules/.pnpm/openai@4.47.3/node_modules/openai/core.mjs:256:25)     
    at OpenAI.makeRequest (file:///D:/document/Github/mi-gpt-2/node_modules/.pnpm/openai@4.47.3/node_modules/openai/core.mjs:299:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async OpenAIClient.chatStream (file:///D:/document/Github/mi-gpt-2/node_modules/.pnpm/mi-gpt@2.1.1/node_modules/mi-gpt/dist/index.js:1086:20) {
  status: 401,
  headers: {
    connection: 'keep-alive',
    'content-length': '83',
    'content-type': 'application/json; charset=utf-8',
    date: 'Mon, 03 Jun 2024 01:37:18 GMT',
    server: 'nginx',
    'server-timing': 'inner; dur=37',
    'strict-transport-security': 'max-age=15724800; includeSubDomains',
    vary: 'Origin'
  },
  request_id: undefined,
  error: {
    message: 'Incorrect API key provided',
    type: 'incorrect_api_key_error'
  },
  code: undefined,
  param: undefined,
  type: 'incorrect_api_key_error'
}

**Comment by idootop** [comment]
兄弟不要直接把 API Key 发出来，已经泄漏了，建议 revoke 掉。你可以 clone 下本仓库切换到最新的 example 分支，然后安装下依赖，再把你的 .env 配置好，在 VS Code 里按 F5 启动调试，看看是否正常。

**Comment by csjuXYZ** [comment]
> 我刚刚用你上面发的 env 参数测试也是可以正常响应的。兄弟不要直接把 API Key 发出来，已经泄漏了，建议 revoke 掉。你可以 clone 下本仓库切换到最新的 example 分支，然后安装下依赖，再把你的 .env 配置好，在 VS Code 里按 F5 启动调试，看看是否正常。

好的，我按你的方法再试一下，这个key我会重新生成，没有关系

**Comment by csjuXYZ** [comment]
跑不通，不折腾了
