### ISSUE TITLE
docker部署启动小米登录返回ECONNREFUSED

### ISSUE THREAD

**Issue by yuzg667** [idootop/mi-gpt#183]
我是用docker部署的，音箱和migpt的docker在同一个局域网，我确认自己的小米id和密码是正确的。但报了如下错误。
```node.js v20.15.0
端口： 36592
登录认证： 已启用


/ $$      /$$ /$$   /$$$$$$  /$$$$$$$ /$$$$$$$$$
| $$$    /$$$|__/ /$$__  $$| $$__  $$|__  $$__/
| $$$$  /$$$$ /$$| $$  \__/| $$  \ $$   | $$   
| $$ $$/$$ $$| $$| $$ /$$$$| $$$$$$$/   | $$   
| $$  $$$| $$| $$| $$|_  $$| $$____/    | $$   
| $$\  $ | $$| $$| $$  \ $$| $$         | $$   
| $$ \/  | $$| $$|  $$$$$$/| $$         | $$   
|__/     |__/|__/ \______/ |__/         |__/                         
                                                                                                                 
         MiGPT v4.1.0  by: del.wang


❌ 登录失败 {
  isError: true,
  code: 'ECONNREFUSED',
  message: '未知',
  error: {
    request: {
      method: 'get',
      url: 'https://account.xiaomi.com/pass/serviceLogin?sid=micoapi&_json=true&_locale=zh_CN',
      headers: '{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded","Accept-Encoding":"gzip, deflate","User-Agent":"Dalvik/2.1.0 (Linux; U; Android 10; RMX2111 Build/QP1A.190711.020) APP/xiaomi.mico APPV/2004040 MK/Uk1YMjExMQ== PassportSDK/3.8.3 passport-ui/3.8.3","Cookie":"userId=xxxx; deviceId=android_1aa39088-bf22-4cfa-8c58-53aa12f96619; passToken=;"}',
      data: '{}'
    },
    response: undefined
  }
}
❌ 登录失败 {
  isError: true,
  code: 'ECONNREFUSED',
  message: '未知',
  error: {
    request: {
      method: 'get',
      url: 'https://account.xiaomi.com/pass/serviceLogin?sid=xiaomiio&_json=true&_locale=zh_CN',
      headers: '{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded","Accept-Encoding":"gzip, deflate","User-Agent":"Dalvik/2.1.0 (Linux; U; Android 10; RMX2111 Build/QP1A.190711.020) APP/xiaomi.mico APPV/2004040 MK/Uk1YMjExMQ== PassportSDK/3.8.3 passport-ui/3.8.3","Cookie":"userId=xxxx; deviceId=android_4c6179e1-02b3-4a63-85c0-xxxxx; passToken=;"}',
      data: '{}'
    },
    response: undefined
  }
}
2024/09/05 12:18:24 Speaker ❌ 初始化 Mi Services 失败
2024/09/05 12:18:24 database ❌  Error: ❌ Assertion failed
    at _LoggerManager.assert (file:///usr/local/lib/node_modules/migpt-server/node_modules/mi-gpt/dist/index.js:259:13)
    at __Logger.assert (file:///usr/local/lib/node_modules/migpt-server/node_modules/mi-gpt/dist/index.js:296:19)
    at AISpeaker.initMiServices (file:///usr/local/lib/node_modules/migpt-server/node_modules/mi-gpt/dist/index.js:476:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async AISpeaker.run (file:///usr/local/lib/node_modules/migpt-server/node_modules/mi-gpt/dist/index.js:748:5)```

**Comment by idootop** [comment]
按照 FAQ 里的这个方法处理

<img width="1231" alt="图片" src="https://github.com/user-attachments/assets/d706211a-b8e7-483c-9502-e593af9635bc">
