### ISSUE TITLE
大佬，请问在.env里已配置好豆包的参数，为啥docker里启动后，还是显示APIConnectionError

### ISSUE THREAD

**Issue by wsy54187** [idootop/mi-gpt#191]
我的.env配置如下：
# OpenAI（也支持通义千问、MoonShot、DeepSeek 等模型）
OPENAI_MODEL=ep-20240927170012-5f66w
OPENAI_API_KEY=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
# OPENAI_BASE_URL=https://ark.cn-beijing.volces.com/api/v3

# Azure OpenAI Service（可选）
# OPENAI_API_VERSION=2024-04-01-preview
# AZURE_OPENAI_API_KEY=你的密钥
# AZURE_OPENAI_ENDPOINT=https://你的资源名.openai.azure.com
# AZURE_OPENAI_DEPLOYMENT=你的模型部署名，比如：gpt-35-turbo-instruct

# 提示音效（可选，一般不用填，你也可以换上自己的提示音链接试试看效果）
# AUDIO_SILENT=静音音频链接，示例：https://example.com/slient.wav
# AUDIO_BEEP=默认提示音链接，同上
# AUDIO_ACTIVE=唤醒提示音链接，同上
# AUDIO_ERROR=出错了提示音链接，同上

# 第三方 TTS（可选，用于调用第三方 TTS 服务）
# TTS_BASE_URL=你的 TTS 接口地址，比如：http://[你的局域网/公网地址]:[端口]/api，比如：http://192.168.31.205:4321/api

然后log是这样的：
2024-09-27 23:48:38 2024/09/27 15:48:38 Speaker ✅ 服务已启动...
2024-09-27 23:49:13 2024/09/27 15:49:13 Speaker 🔥 打开傻妞
2024-09-27 23:49:13 2024/09/27 15:49:13 Speaker 🔊 你好，我是傻妞，很高兴认识你
2024-09-27 23:49:24 2024/09/27 15:49:24 Speaker 🔥 你自己
2024-09-27 23:49:25 2024/09/27 15:49:25 Speaker 🔊 请稍等
2024-09-27 23:49:32 2024/09/27 15:49:32 Open AI ❌ LLM 响应异常 APIConnectionError: Connection error.
2024-09-27 23:49:32     at OpenAI.makeRequest (/app/node_modules/.pnpm/openai@4.56.0/node_modules/openai/core.js:304:19)
2024-09-27 23:49:32     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-09-27 23:49:32     at async OpenAIClient.chatStream (/app/dist/index.cjs:1253:20) {
2024-09-27 23:49:32   status: undefined,
2024-09-27 23:49:32   headers: undefined,
2024-09-27 23:49:32   request_id: undefined,
2024-09-27 23:49:32   error: undefined,
2024-09-27 23:49:32   code: undefined,
2024-09-27 23:49:32   param: undefined,
2024-09-27 23:49:32   type: undefined,
2024-09-27 23:49:32   cause: FetchError: request to https://api.openai.com/v1/chat/completions failed, reason: 
2024-09-27 23:49:32       at ClientRequest.<anonymous> (/app/node_modules/.pnpm/node-fetch@2.7.0/node_modules/node-fetch/lib/index.js:1501:11)
2024-09-27 23:49:32       at ClientRequest.emit (node:events:519:28)
2024-09-27 23:49:32       at TLSSocket.socketErrorListener (node:_http_client:500:9)
2024-09-27 23:49:32       at TLSSocket.emit (node:events:519:28)
2024-09-27 23:49:32       at emitErrorNT (node:internal/streams/destroy:169:8)
2024-09-27 23:49:32       at emitErrorCloseNT (node:internal/streams/destroy:128:3)
2024-09-27 23:49:32       at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
2024-09-27 23:49:32     type: 'system',
2024-09-27 23:49:32     errno: 'ETIMEDOUT',
2024-09-27 23:49:32     code: 'ETIMEDOUT'
2024-09-27 23:49:32   }
2024-09-27 23:49:32 }
2024-09-27 23:49:32 2024/09/27 15:49:32 Speaker 🔊 啊哦，出错了，请稍后再试吧！
2024-09-27 23:50:06 2024/09/27 15:50:06 Speaker 🔊 傻妞已退出
2024-09-28 00:00:02 2024/09/27 16:00:02 Speaker 🔥 三个小时后关闭智能插座
2024-09-28 00:00:09 2024/09/27 16:00:09 Speaker 🔥 两个小时后关闭智能插座
2024-09-28 00:23:27 2024/09/27 16:23:27 Speaker 🔥 召唤傻妞
2024-09-28 00:23:28 2024/09/27 16:23:28 Speaker 🔊 你好，我是傻妞，很高兴认识你
2024-09-28 00:23:42 2024/09/27 16:23:42 Speaker 🔥 请介绍一下你自己
2024-09-28 00:23:43 2024/09/27 16:23:43 Speaker 🔊 让我先想想
2024-09-28 00:23:48 2024/09/27 16:23:48 Open AI ❌ LLM 响应异常 APIConnectionError: Connection error.
2024-09-28 00:23:48     at OpenAI.makeRequest (/app/node_modules/.pnpm/openai@4.56.0/node_modules/openai/core.js:304:19)
2024-09-28 00:23:48     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-09-28 00:23:48     at async OpenAIClient.chatStream (/app/dist/index.cjs:1253:20) {
2024-09-28 00:23:48   status: undefined,
2024-09-28 00:23:48   headers: undefined,
2024-09-28 00:23:48   request_id: undefined,
2024-09-28 00:23:48   error: undefined,
2024-09-28 00:23:48   code: undefined,
2024-09-28 00:23:48   param: undefined,
2024-09-28 00:23:48   type: undefined,
2024-09-28 00:23:48   cause: FetchError: request to https://api.openai.com/v1/chat/completions failed, reason: 
2024-09-28 00:23:48       at ClientRequest.<anonymous> (/app/node_modules/.pnpm/node-fetch@2.7.0/node_modules/node-fetch/lib/index.js:1501:11)
2024-09-28 00:23:48       at ClientRequest.emit (node:events:519:28)
2024-09-28 00:23:48       at TLSSocket.socketErrorListener (node:_http_client:500:9)
2024-09-28 00:23:48       at TLSSocket.emit (node:events:519:28)
2024-09-28 00:23:48       at emitErrorNT (node:internal/streams/destroy:169:8)
2024-09-28 00:23:48       at emitErrorCloseNT (node:internal/streams/destroy:128:3)
2024-09-28 00:23:48       at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
2024-09-28 00:23:48     type: 'system',
2024-09-28 00:23:48     errno: 'ETIMEDOUT',
2024-09-28 00:23:48     code: 'ETIMEDOUT'
2024-09-28 00:23:48   }
2024-09-28 00:23:48 }
2024-09-28 00:23:49 2024/09/27 16:23:49 Speaker 🔊 啊哦，出错了，请稍后再试吧！

相同的豆包参数，在migpt-gui前端页面配置后，可以正常调用ai，但在.env里配置后就不行。。。请大佬解惑谢谢！

**Comment by idootop** [comment]
你没修改豆包的 OPENAI_BASE_URL

**Comment by wsy54187** [comment]
> 你没修改豆包的 OPENAI_BASE_URL

![1](https://github.com/user-attachments/assets/fe00c4c0-a215-45b1-97ee-3cb8b13e7c7e)
![2](https://github.com/user-attachments/assets/a12c85ec-621b-4b83-92bb-a4dc97c5f7e3)
大佬已按教程改过了，你看我的.env和豆包教程里的OPENAI_BASE_URL是一样的

**Comment by wsy54187** [comment]
> 你没修改豆包的 OPENAI_BASE_URL

OPENAI_BASE_URL=https://ark.cn-beijing.volces.com/api/v3/chat/completions
和
OPENAI_BASE_URL=https://ark.cn-beijing.volces.com/api/v3/
都试过了，还是不行
求助大佬，看到后麻烦解答下，谢谢
