### ISSUE TITLE
新的登录失败错误，有遇到的么？ code: 'ECONNABORTED',

### ISSUE THREAD

**Issue by hcling97** [idootop/mi-gpt#196]
MiGPT v4.2.0  by: del.wang

❌ 登录失败 {
  isError: true,
  code: 'ECONNABORTED',
  message: 'timeout of 5000ms exceeded',
  error: {
    request: {
      method: 'get',
      url: 'https://account.xiaomi.com/pass/serviceLogin?sid=micoapi&_json=true&_locale=zh_CN',
      headers: '{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded","Accept-Encoding":"gzip, deflate","User-Agent":"Dalvik/2.1.0 (Linux; U; Android 10; RMX2111 Build/QP1A.190711.020) APP/xiaomi.mico APPV/2004040 MK/Uk1YMjExMQ== PassportSDK/3.8.3 passport-ui/3.8.3","Cookie":"userId=1155192416; deviceId=android_5d8ec752-6d79-42b0-99e5-2dd0db65adf4; passToken=;"}',
      data: '{}'
    },
    response: undefined
  }
}
❌ 登录失败 {
  isError: true,
  code: 'ECONNABORTED',
  message: 'timeout of 5000ms exceeded',
  error: {
    request: {
      method: 'get',
      url: 'https://account.xiaomi.com/pass/serviceLogin?sid=xiaomiio&_json=true&_locale=zh_CN',
      headers: '{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded","Accept-Encoding":"gzip, deflate","User-Agent":"Dalvik/2.1.0 (Linux; U; Android 10; RMX2111 Build/QP1A.190711.020) APP/xiaomi.mico APPV/2004040 MK/Uk1YMjExMQ== PassportSDK/3.8.3 passport-ui/3.8.3","Cookie":"userId=1155192416; deviceId=android_507be3a0-328a-48e0-959b-9030dfce83d6; passToken=;"}',
      data: '{}'
    },
    response: undefined
  }
}
2024/10/02 15:10:44 Speaker ❌ 初始化 Mi Services 失败
2024/10/02 15:10:44 database ❌  Error: ❌ Assertion failed
    at _LoggerManager.assert (/app/dist/index.cjs:282:13)
    at __Logger.assert (/app/dist/index.cjs:319:19)
    at AISpeaker.initMiServices (/app/dist/index.cjs:499:17)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:540:9)
    at process.processTimers (node:internal/timers:514:7)
    at async AISpeaker.run (/app/dist/index.cjs:771:5)
    at async main (file:///app/app.js:6:3)

**Comment by hcling97** [comment]
直接get访问请求地址似乎没有问题：
&&&START&&&{"notificationUrl":"","code":0,"description":"成功","securityStatus":0,"userId":1155192416,"cUserId":"CieJ1hjK6NmqVHGGfN4XCgQ0EfQ","result":"ok","psecurity":"C76+Ezi2sPO8jW7H96d6xQ==","captchaUrl":null,"location":"https://sts.api.io.mi.com/sts?d=wb_7171be22-dbe2-43b5-92d7-f66d240f1027&ticket=0&pwd=0&p_ts=1727879978000&fid=0&p_lm=1&auth=LjEQ5KIxK9PYJbDFYzsnwrYN5fiMiMiEu1lAevuUSAIyehGL4QlKpi7rmNFWS%2FB6MRKYU5ArZpUXMkGkdMyHf2qoqyZsvymti4tOLuCzQBdwd3tG5ZkcJt1aR%2B3sCSZN0jBqofCbks0f3rdpNc%2BBXsaChmN6vkDxtlFW51uuY5k%3D&m=1&_group=DEFAULT&tsl=0&p_ca=0&p_ur=CN&p_idc=China&nonce=R9EfPSm2LzIBt2xa&_ssign=G7WpbrrCmHzZYNzxBCPc5qVkgjI%3D","pwd":1,"child":0,"desc":"成功"}

**Comment by hcling97** [comment]
发现是container内部的dns有问题，直接用--net=host参数解决了。
