### ISSUE TITLE
docker运行失败

### ISSUE THREAD

**Issue by BarryYin** [idootop/mi-gpt#200]
(base) mac@macmingdeMacBook-Pro mi-gpt % docker run -d --env-file $(pwd)/.env -v $(pwd)/.migpt.js:/app/.migpt.js idootop/mi-gpt:latest
6ea6ce075b9b346f1f2fa33d13c98a7f05dc5d95cc6f94daf6f87d375fce1311

**Comment by idootop** [comment]
请至少贴出 docker 容器运行日志，以及先了解下 docker 如何使用。

**Comment by BarryYin** [comment]
2024-10-15 10:03:37 
2024-10-15 10:03:37 
2024-10-15 10:03:39 🐛 请检查你的 did 与米家中的设备名称是否一致。注意错别字、空格和大小写，比如：音响 👉 音箱
2024-10-15 09:47:15 ❌ 找不到设备：小米小爱音箱Play 增强版
2024-10-15 09:47:16 2024/10/15 01:47:16 Speaker ❌ 初始化 Mi Services 失败
2024-10-15 09:47:16 2024/10/15 01:47:16 database ❌  Error: ❌ Assertion failed
2024-10-15 09:47:16     at _LoggerManager.assert (/app/dist/index.cjs:282:13)
2024-10-15 09:47:16     at __Logger.assert (/app/dist/index.cjs:319:19)
2024-10-15 09:47:16     at AISpeaker.initMiServices (/app/dist/index.cjs:499:17)
2024-10-15 09:47:16     at async AISpeaker.run (/app/dist/index.cjs:771:5)
2024-10-15 09:47:16     at async main (file:///app/app.js:6:3)
2024-10-15 10:03:39 ❌ 找不到设备：小米小爱音箱Play 增强版
2024-10-15 10:03:39 2024/10/15 02:03:39 Speaker ❌ 初始化 Mi Services 失败
2024-10-15 10:03:39 2024/10/15 02:03:39 database ❌  Error: ❌ Assertion failed
2024-10-15 10:03:39     at _LoggerManager.assert (/app/dist/index.cjs:282:13)
2024-10-15 10:03:39     at __Logger.assert (/app/dist/index.cjs:319:19)
2024-10-15 10:03:39     at AISpeaker.initMiServices (/app/dist/index.cjs:499:17)
2024-10-15 10:03:39     at async AISpeaker.run (/app/dist/index.cjs:771:5)
2024-10-15 10:03:39     at async main (file:///app/app.js:6:3)

**Comment by BarryYin** [comment]
> 2024-10-15 10:03:37 2024-10-15 10:03:37 2024-10-15 10:03:39 🐛 请检查你的 did 与米家中的设备名称是否一致。注意错别字、空格和大小写，比如：音响 👉 音箱 2024-10-15 09:47:15 ❌ 找不到设备：小米小爱音箱Play 增强版 2024-10-15 09:47:16 2024/10/15 01:47:16 Speaker ❌ 初始化 Mi Services 失败 2024-10-15 09:47:16 2024/10/15 01:47:16 database ❌ Error: ❌ Assertion failed 2024-10-15 09:47:16 at _LoggerManager.assert (/app/dist/index.cjs:282:13) 2024-10-15 09:47:16 at __Logger.assert (/app/dist/index.cjs:319:19) 2024-10-15 09:47:16 at AISpeaker.initMiServices (/app/dist/index.cjs:499:17) 2024-10-15 09:47:16 at async AISpeaker.run (/app/dist/index.cjs:771:5) 2024-10-15 09:47:16 at async main (file:///app/app.js:6:3) 2024-10-15 10:03:39 ❌ 找不到设备：小米小爱音箱Play 增强版 2024-10-15 10:03:39 2024/10/15 02:03:39 Speaker ❌ 初始化 Mi Services 失败 2024-10-15 10:03:39 2024/10/15 02:03:39 database ❌ Error: ❌ Assertion failed 2024-10-15 10:03:39 at _LoggerManager.assert (/app/dist/index.cjs:282:13) 2024-10-15 10:03:39 at __Logger.assert (/app/dist/index.cjs:319:19) 2024-10-15 10:03:39 at AISpeaker.initMiServices (/app/dist/index.cjs:499:17) 2024-10-15 10:03:39 at async AISpeaker.run (/app/dist/index.cjs:771:5) 2024-10-15 10:03:39 at async main (file:///app/app.js:6:3)

这个did是不是就是在米家中的音箱的名字呀

**Comment by idootop** [comment]
一般复制米家中的名称即可（不支持共享设备），具体看 FAQ

**Comment by BarryYin** [comment]
查看docker信息，；找到授权链接，在授权跳到小米网站的时候，出现：未授权请求或授权失效 21301 ,请重试（the request is unauthorized or invalid）

**Comment by BarryYin** [comment]
![image](https://github.com/user-attachments/assets/f8e1344c-5523-49eb-8214-a753e5db7daf)
已经可以运行了，但是小爱音响不输出语音，只是大模型在跑

**Comment by idootop** [comment]
检查你的tts指令参数是否和你的设备匹配
