### ISSUE TITLE
Open AI ❌ LLM 响应异常 NotFoundError: 404 status code (no body)

### ISSUE THREAD

**Issue by jiangjin1999** [idootop/mi-gpt#218]
2024-12-10 23:50:53 2024/12/10 15:50:53 Open AI ❌ LLM 响应异常 NotFoundError: 404 status code (no body)
2024-12-10 23:50:53     at APIError.generate (/app/node_modules/.pnpm/openai@4.56.0/node_modules/openai/error.js:54:20)
2024-12-10 23:50:53     at OpenAI.makeStatusError (/app/node_modules/.pnpm/openai@4.56.0/node_modules/openai/core.js:275:33)
2024-12-10 23:50:53     at OpenAI.makeRequest (/app/node_modules/.pnpm/openai@4.56.0/node_modules/openai/core.js:318:30)
2024-12-10 23:50:53     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-12-10 23:50:53     at async OpenAIClient.chatStream (/app/dist/index.cjs:1253:20) {
2024-12-10 23:50:53   status: 404,
2024-12-10 23:50:53   headers: {
2024-12-10 23:50:53     'access-control-allow-credentials': 'true',
2024-12-10 23:50:53     connection: 'close',
2024-12-10 23:50:53     'content-length': '0',
2024-12-10 23:50:53     date: 'Tue, 10 Dec 2024 15:50:53 GMT',
2024-12-10 23:50:53     server: 'nginx/1.18.0 (Ubuntu)',
2024-12-10 23:50:53     'set-cookie': 'HWWAFSESTIME=1733845850892; path=/, HWWAFSESID=1fe5664ca0bc136c17f; path=/',
2024-12-10 23:50:53     vary: 'origin, access-control-request-method, access-control-request-headers',
2024-12-10 23:50:53     'x-ds-trace-id': 'bfe65d7f46ed15a435c21d95e5d0f18f'
2024-12-10 23:50:53   },
2024-12-10 23:50:53   request_id: undefined,
2024-12-10 23:50:53   error: undefined,
2024-12-10 23:50:53   code: undefined,
2024-12-10 23:50:53   param: undefined,
2024-12-10 23:50:53   type: undefined
2024-12-10 23:50:53 }
2024-12-10 23:50:53 2024/12/10 15:50:53 Speaker 🔊 啊哦，出错了，请稍后再试吧！

1. 本地python调用api对话没问题（网络，key，url，模型）

issuse里没找到这个问题，求大佬解答。

**Comment by jiangjin1999** [comment]
已解决：
OPENAI_BASE_URL=https://api.deepseek.com/v1 #你的大模型接口的 baseURL，比如：https://api.openai.com/v1（注意：一般以 /v1 结尾）
这个OPENAI_BASE_URL的所在行不能加注释。
（python🐶致歉）
