### ISSUE TITLE
豆包接入报404，是什么原因呢？

### ISSUE THREAD

**Issue by gujian2git** [idootop/mi-gpt#227]
配置如下
OPENAI_MODEL=ep-20----
OPENAI_API_KEY=af516xxxxxxx
OPENAI_BASE_URL=https://ark.cn-beijing.volces.com/api/v3

2024-12-25 21:02:41 2024/12/25 13:02:41 Speaker 🔊 让我先想想
2024-12-25 21:02:42 2024/12/25 13:02:42 Open AI ❌ LLM 响应异常 NotFoundError: 404 status code (no body)
2024-12-25 21:02:42     at APIError.generate (/app/node_modules/.pnpm/openai@4.56.0/node_modules/openai/error.js:54:20)
2024-12-25 21:02:42     at OpenAI.makeStatusError (/app/node_modules/.pnpm/openai@4.56.0/node_modules/openai/core.js:275:33)
2024-12-25 21:02:42     at OpenAI.makeRequest (/app/node_modules/.pnpm/openai@4.56.0/node_modules/openai/core.js:318:30)
2024-12-25 21:02:42     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-12-25 21:02:42     at async OpenAIClient.chatStream (/app/dist/index.cjs:1253:20) {
2024-12-25 21:02:42   status: 404,
2024-12-25 21:02:42   headers: {
2024-12-25 21:02:42     connection: 'close',
2024-12-25 21:02:42     'content-length': '0',
2024-12-25 21:02:42     date: 'Wed, 25 Dec 2024 13:02:39 GMT',
2024-12-25 21:02:42     server: 'istio-envoy'
2024-12-25 21:02:42   },
2024-12-25 21:02:42   request_id: undefined,
2024-12-25 21:02:42   error: undefined,
2024-12-25 21:02:42   code: undefined,
2024-12-25 21:02:42   param: undefined,
2024-12-25 21:02:42   type: undefined
2024-12-25 21:02:42 }

**Comment by idootop** [comment]
提问之前请先阅读 FAQ。 https://github.com/idootop/mi-gpt/blob/main/docs/faq.md#q%E9%99%A4%E4%BA%86-openai-%E8%BF%98%E6%94%AF%E6%8C%81%E5%93%AA%E4%BA%9B%E6%A8%A1%E5%9E%8B%E5%A6%82%E4%BD%95%E8%AE%BE%E7%BD%AE
