### ISSUE TITLE
LLM 响应异常APIConnectionError: Connection error.

### ISSUE THREAD

**Issue by qwe134** [idootop/mi-gpt#232]
2024/12/31 15:32:13 Speaker ? ?????...
2024/12/31 15:32:22 Speaker ? ????
2024/12/31 15:32:24 Speaker ? ??????????????
2024/12/31 15:32:33 Speaker ? ??????
2024/12/31 15:32:34 Speaker ? ?????
2024/12/31 15:32:39 Open AI ? LLM 响应异常 APIConnectionError: Connection error.
    at OpenAI.makeRequest (/app/node_modules/.pnpm/openai@4.56.0/node_modules/openai/core.js:304:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async OpenAIClient.chatStream (/app/dist/index.cjs:1253:20) {
  status: undefined,
  headers: undefined,
  request_id: undefined,
  error: undefined,
  code: undefined,
  param: undefined,
  type: undefined,
  cause: FetchError: request to http://127.0.0.1:11434/v1/chat/completions failed, reason: connect ECONNREFUSED 127.0.0.1:11434
      at ClientRequest.<anonymous> (/app/node_modules/.pnpm/node-fetch@2.7.0/node_modules/node-fetch/lib/index.js:1501:11)
      at ClientRequest.emit (node:events:519:28)
      at Socket.socketErrorListener (node:_http_client:500:9)
      at Socket.emit (node:events:519:28)
      at emitErrorNT (node:internal/streams/destroy:169:8)
      at emitErrorCloseNT (node:internal/streams/destroy:128:3)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
    type: 'system',
    errno: 'ECONNREFUSED',
    code: 'ECONNREFUSED'
  }
}

本地部署的qwen，ollama run可以正常运行，调用就出错
OPENAI_MODEL=qwen2.5:7b:latest
OPENAI_API_KEY=ollama
OPENAI_BASE_URL=http://127.0.0.1:11434/v1

**Comment by idootop** [comment]
Docker 内部的系统是独立于宿主机的。
Docker 里的 127.0.0.1 != 宿主系统 127.0.0.1。
至于怎么在 Docker 内部访问宿主系统的本地服务，自行百度。
