### ISSUE TITLE
LLM 响应异常 PermissionDeniedError: 403 <html>

### ISSUE THREAD

**Issue by MilkTeaNo7** [idootop/mi-gpt#33]
```
2024/06/06 16:02:05 Open AI ❌ LLM 响应异常 PermissionDeniedError: 403 <html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>cloudflare</center>
</body>
</html>
    at APIError.generate (/app/node_modules/.pnpm/openai@4.47.3/node_modules/openai/error.js:51:20)
    at OpenAI.makeStatusError (/app/node_modules/.pnpm/openai@4.47.3/node_modules/openai/core.js:263:33)
    at OpenAI.makeRequest (/app/node_modules/.pnpm/openai@4.47.3/node_modules/openai/core.js:306:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async OpenAIClient.chat (/app/dist/index.cjs:1105:28)
    at async ShortTermMemoryAgent.generate (/app/dist/index.cjs:1917:17)
    at async MemoryManager._updateShortTermMemory (/app/dist/index.cjs:2016:23)
    at async MemoryManager.updateLongShortTermMemory (/app/dist/index.cjs:1993:21) {
  status: 403,

  headers: {
    'alt-svc': 'h3=":443"; ma=86400',
    'cf-ray': '88f99ff0bad87c72-HYD',
    connection: 'keep-alive',
    'content-encoding': 'gzip',
    'content-type': 'text/html',
    date: 'Thu, 06 Jun 2024 16:02:05 GMT',
    server: 'cloudflare',
    'set-cookie': '__cf_bm=yiE2le26NzcLDqhy5iZajc19weDdrGMIYaKtkIwSAis-1717689725-1.0.1.1-TyI97lXVwljvygGYrXuz.HUbD80dtCTR.HoRPLzuOk32jt6FSYRssKtde5Yh_x61XHDRHfhtD6askVe832DJ7A; path=/; expires=Thu, 06-Jun-24 16:32:05 GMT; domain=.api.openai.com; HttpOnly; Secure; SameSite=None, _cfuvid=uFMqAhMqb8WCLDWVNt0OifCW6dtMjM3BVAQ.qehKFws-1717689725601-0.0.1.1-604800000; path=/; domain=.api.openai.com; HttpOnly; Secure; SameSite=None',
    'transfer-encoding': 'chunked',
    vary: 'Accept-Encoding'
  },
  request_id: undefined,
  error: undefined,
  code: undefined,
  param: undefined,
  type: undefined
}

问题如上，我使用了kimi，API已经更换，不知道问题是哈

**Comment by idootop** [comment]
目测是因为你的代理 IP 被 cloudflare 风控了，切换节点试试。或者把环境变量里的 HTTP_PROXY 设置成空字符串，关闭代理。

**Comment by zhenghuanqi** [comment]
请问在哪个文件里HTTP_PROXY 设置成空字符串 HTTP_PROXY='' ，我是使用docker 部署的
![Uploading photo_2024-10-20_17-51-11.jpg…]()
