### ISSUE TITLE
一直提示LLM 响应异常，换了几个模型都报错

### ISSUE THREAD

**Issue by haoshuhua189** [idootop/mi-gpt#36]
你好，帮忙看下为啥一直出现这个错误

2024-06-07 13:45:45 2024/06/07 05:45:45 Speaker ✅ 服务已启动...
2024-06-07 13:46:00 2024/06/07 05:46:00 Speaker 🔥 召唤傻妞
2024-06-07 13:46:01 2024/06/07 05:46:01 Speaker 🔊 你好，我是傻妞，很高兴认识你
2024-06-07 13:46:09 2024/06/07 05:46:09 Speaker 🔥 你在做什么
2024-06-07 13:46:09 2024/06/07 05:46:09 Speaker 🔊 让我先想想
2024-06-07 13:47:17 2024/06/07 05:47:17 Open AI ❌ LLM 响应异常 APIConnectionError: Connection error.
2024-06-07 13:47:17     at OpenAI.makeRequest (/app/node_modules/.pnpm/openai@4.47.3/node_modules/openai/core.js:292:19)
2024-06-07 13:47:17     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-06-07 13:47:17     at async OpenAIClient.chatStream (/app/dist/index.cjs:1147:20) {
2024-06-07 13:47:17   status: undefined,
2024-06-07 13:47:17   headers: undefined,
2024-06-07 13:47:17   request_id: undefined,
2024-06-07 13:47:17   error: undefined,
2024-06-07 13:47:17   code: undefined,
2024-06-07 13:47:17   param: undefined,
2024-06-07 13:47:17   type: undefined,
2024-06-07 13:47:17   cause: FetchError: request to https://api.openai.com/v1/chat/completions failed, reason: connect ECONNREFUSED 108.160.169.37:443
2024-06-07 13:47:17       at ClientRequest.<anonymous> (/app/node_modules/.pnpm/node-fetch@2.7.0/node_modules/node-fetch/lib/index.js:1501:11)
2024-06-07 13:47:17       at ClientRequest.emit (node:events:519:28)
2024-06-07 13:47:17       at TLSSocket.socketErrorListener (node:_http_client:500:9)
2024-06-07 13:47:17       at TLSSocket.emit (node:events:531:35)
2024-06-07 13:47:17       at emitErrorNT (node:internal/streams/destroy:169:8)
2024-06-07 13:47:17       at emitErrorCloseNT (node:internal/streams/destroy:128:3)
2024-06-07 13:47:17       at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
2024-06-07 13:47:17     type: 'system',
2024-06-07 13:47:17     errno: 'ECONNREFUSED',
2024-06-07 13:47:17     code: 'ECONNREFUSED'
2024-06-07 13:47:17   }
2024-06-07 13:47:17 }
2024-06-07 13:47:17 2024/06/07 05:47:17 Speaker 🔊 啊哦，出错了，请稍后再试吧！

**Comment by idootop** [comment]
网络异常，OpenAI 的服务在国内需要配代理才能访问。参考这个 issue: https://github.com/idootop/mi-gpt/issues/29#issuecomment-2152330176

**Comment by haoshuhua189** [comment]
了解了，感谢回复
