### ISSUE TITLE
 Open AI ❌ LLM 响应异常 NotFoundError: 404 "Not Found"

### ISSUE THREAD

**Issue by enilu** [idootop/mi-gpt#43]
问问题的时候报错：
```
/ $$      /$$ /$$   /$$$$$$  /$$$$$$$ /$$$$$$$$$
| $$$    /$$$|__/ /$$__  $$| $$__  $$|__  $$__/
| $$$$  /$$$$ /$$| $$  \__/| $$  \ $$   | $$
| $$ $$/$$ $$| $$| $$ /$$$$| $$$$$$$/   | $$
| $$  $$$| $$| $$| $$|_  $$| $$____/    | $$
| $$\  $ | $$| $$| $$  \ $$| $$         | $$
| $$ \/  | $$| $$|  $$$$$$/| $$         | $$
|__/     |__/|__/ \______/ |__/         |__/

         MiGPT v3.0.1  by: del.wang


2024/06/08 01:29:12 Speaker ✅ 服务已启动...
2024/06/08 01:29:22 Speaker 🔥 请问明天天气如何
2024/06/08 01:29:23 Speaker 🔊 请稍等
2024/06/08 01:29:27 Open AI ❌ LLM 响应异常 NotFoundError: 404 "Not Found"
    at APIError.generate (D:\workspace\mi-gpt\node_modules\.pnpm\openai@4.49.0\node_modules\openai\error.js:54:20)
    at OpenAI.makeStatusError (D:\workspace\mi-gpt\node_modules\.pnpm\openai@4.49.0\node_modules\openai\core.js:263:33)
    at OpenAI.makeRequest (D:\workspace\mi-gpt\node_modules\.pnpm\openai@4.49.0\node_modules\openai\core.js:306:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async OpenAIClient.chatStream (D:\workspace\mi-gpt\dist\index.cjs:1145:20) {
  status: 404,
  headers: {
    'access-control-allow-credentials': 'true',
    'access-control-allow-headers': 'Content-Type,Authorization,x-xsrf-token,x-platform,X-PLATFORM',
    'access-control-allow-methods': 'GET,POST, OPTIONS',
    'access-control-max-age': '86400',
    'cache-control': 'no-cache, no-store, max-age=0, must-revalidate',
    connection: 'keep-alive',
    'content-encoding': 'gzip',
    'content-type': 'application/json',
    date: 'Fri, 07 Jun 2024 17:29:27 GMT',
    expires: '0',
    pragma: 'no-cache',
    'req-arrive-time': '1717781367463',
    'req-cost-time': '9',
    'resp-start-time': '1717781367473',
    server: 'istio-envoy',
    'set-cookie': 'XSRF-TOKEN=54108ebc-c0ba-4d86-8830-1b97a2dbb423; Path=/',
    'transfer-encoding': 'chunked',
    vary: 'Accept-Encoding,Origin,Access-Control-Request-Method,Access-Control-Request-Headers',
    'x-content-type-options': 'nosniff',
    'x-envoy-upstream-service-time': '9',
    'x-frame-options': 'SAMEORIGIN',
    'x-xss-protection': '1; mode=block'
  },
  request_id: undefined,
  error: 'Not Found',
  code: undefined,
  param: undefined,
  type: undefined
}
2024/06/08 01:29:27 Speaker 🔊 啊哦，出错了，请稍后再试吧！
```

是因为没有识别env配置文件吗？

但是已经按照readme中的下面说明做了配置了

```
Q：我 Clone 了这个仓库，但是本地启动失败

如果你是通过 clone 本项目仓库的方式来运行，记得在 start 之前先 build 一下。

pnpm install && pnpm build && pnpm start
另外， start 命令默认没有注入 .env 文件里的环境变量。你可以在 VS Code 里按 F5 直接运行，会自动读取 .env ，或者将启动脚本改为：

node --env-file=.env app.js
```

**Comment by idootop** [comment]
目测你的代理 IP 被风控禁止访问了，换个代理节点试试看。

**Comment by idootop** [comment]
目测你的代理 IP 被风控禁止访问了，换个代理节点试试看。

**Comment by morningcui** [comment]
本地部署的ollama，是不是路径不正确，总是提示错误。
环境变量部署如下：
			"OPENAI_MODEL=qwen:1.8b",
			"OPENAI_API_KEY=",
			"OPENAI_BASE_URL=http://192.168.199.199:11434/V1",
![image](https://github.com/user-attachments/assets/7a721494-7442-4908-8cd6-234da5b2eb5f)

**Comment by idootop** [comment]
@morningcui https://ollama.com/blog/openai-compatibility

**Comment by morningcui** [comment]
非常感谢！ 安装了OPEN-WEBUI后，就正常使用了！



***@***.***
 
发件人： Del
发送时间： 2024-09-02 22:44
收件人： idootop/mi-gpt
抄送： morningcui; Mention
主题： Re: [idootop/mi-gpt] Open AI ❌ LLM 响应异常 NotFoundError: 404 "Not Found" (Issue #43)
@morningcui https://ollama.com/blog/openai-compatibility
