### ISSUE TITLE
🔊 支持的小爱音箱型号

### ISSUE THREAD

**Issue by idootop** [idootop/mi-gpt#92]
# 🔊 支持的小爱音箱型号

## ✅ 完美运行

已知可以完美运行 `MiGPT` 的小爱音箱型号有：

> 注意：这里的连续对话是一种实验性功能，并非小爱音箱自带的连续对话。在没有刷机的情况下，使用效果并不理想（仅供尝鲜），建议日常使用时关闭 `streamResponse` 选项。

| 名称                     | 型号                                                                                                | ttsCommand | wakeUpCommand | playingCommand | streamResponse | 反馈来源                                                                          |
| ------------------------ | --------------------------------------------------------------------------------------------------- | ---------- | ------------- | -------------- | -------------- | --------------------------------------------------------------------------------- |
| Xiaomi 智能音箱 Pro      | [OH2P](https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:speaker:0000A015:xiaomi-oh2p:1) | `[7, 3]`   | `[7, 1]`      | -              | true           | [@idootop](https://github.com/idootop)                                            |
| 小爱音箱 Pro             | [LX06](https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:speaker:0000A015:xiaomi-lx06:2) | `[5, 1]`   | `[5, 3]`      | -              | true           | [@idootop](https://github.com/idootop)                                            |
| 小米 AI 音箱             | [S12](https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:speaker:0000A015:xiaomi-s12:2)   | `[5, 1]`   | `[5, 3]`      | -              | true           | 微信: CMSJ                                                                        |
| 小米 AI 音箱（第二代）   | [L15A](https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:speaker:0000A015:xiaomi-l15a:2) | `[7, 3]`   | `[7, 1]`      | `[3, 1, 1]`    | true           | 微信: 龙之广                                                                      |
| 小爱音箱 万能遥控版      | [LX5A](https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:speaker:0000A015:xiaomi-lx5a:2) | `[5, 1]`   | `[5, 3]`      | -              | true           | [@imhsz](https://github.com/idootop/mi-gpt/issues/62)                             |
| 小爱音箱 Play（2019 款） | [LX05](https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:speaker:0000A015:xiaomi-lx05:1) | `[5, 1]`   | `[5, 3]`      | `[3, 1, 1]`    | true           | [@wt666666](https://github.com/idootop/mi-gpt/issues/92#issuecomment-2168424538)  |
| 小爱智能家庭屏 10        | [X10A](https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:speaker:0000A015:xiaomi-x10a:1) | `[7, 3]`   | `[7, 1]`      | -              | true           | [@IDarkBoss](https://github.com/idootop/mi-gpt/issues/92#issuecomment-2190928452) |
| Xiaomi Sound Pro         | [L17A](https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:speaker:0000A015:xiaomi-l17a:1) | `[7, 3]`   | `[7, 1]`      | -              | true           | 微信: eof                                                                         |

## 🚗 正常运行

可以正常运行 `MiGPT`，但不支持连续对话的小爱音箱型号有：

> 部分机型的 MIoT 接口不支持查询设备播放状态或查询状态异常，比如小米音箱 Play 增强版（L05C），将会导致 `MiGPT` 部分功能异常，无法使用连续对话等，此时需要关闭 `streamResponse`。相关 [issue](https://github.com/idootop/mi-gpt/issues/14)

| 名称                          | 型号                                                                                                | ttsCommand | wakeUpCommand | playingCommand | streamResponse | 反馈来源                                                                               |
| ----------------------------- | --------------------------------------------------------------------------------------------------- | ---------- | ------------- | -------------- | -------------- | -------------------------------------------------------------------------------------- |
| 小爱音箱                      | [L06A](https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:speaker:0000A015:xiaomi-l06a:2) | `[5, 1]`   | `[5, 2]`      | -              | false          | [@zhanglc](https://github.com/idootop/mi-gpt/issues/42)                                |
| 小爱音箱 mini                 | [LX01](https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:speaker:0000A015:xiaomi-lx01:1) | `[5, 1]`   | `[5, 2]`      | -              | false          | [@gsscsd](https://github.com/idootop/mi-gpt/issues/92#issuecomment-2168013500)         |
| 小爱音箱 Play                 | [L05B](https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:speaker:0000A015:xiaomi-l05b:1) | `[5, 3]`   | `[5, 1]`      | -              | false          | [@BiuBiu2323](https://github.com/idootop/mi-gpt/issues/48)                             |
| 小米小爱音箱 Play 增强版      | [L05C](https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:speaker:0000A015:xiaomi-l05c:1) | `[5, 3]`   | `[5, 1]`      | -              | false          | [@lyddias](https://github.com/idootop/mi-gpt/issues/14)                                |
| 小爱音箱 Art                  | [L09A](https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:speaker:0000A015:xiaomi-l09a:1) | `[3, 1]`   | `[3, 2]`      | -              | false          | [@zwsn](https://github.com/idootop/mi-gpt/issues/92#issuecomment-2181944065)           |
| 小爱触屏音箱                  | [LX04](https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:speaker:0000A015:xiaomi-lx04:2) | `[5, 1]`   | `[5, 2]`      | -              | false          | [@ilovesouthpark](https://github.com/idootop/mi-gpt/issues/92#issuecomment-2184678990) |
| Xiaomi 智能家庭屏 Mini        | [ASX4B](https://home.miot-spec.com/spec/xiaomi.wifispeaker.x4b)                                     | `[5, 3]`   | `[5, 1]`      | -              | false          | [@VincentGresham](https://github.com/idootop/mi-gpt/issues/92#issuecomment-2645762809) |
| Xiaomi 智能家庭屏 6           | [X6A](https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:speaker:0000A015:xiaomi-x6a:1)   | `[7, 3]`   | `[7, 1]`      | -              | false          | [@Hongwing](https://github.com/idootop/mi-gpt/issues/80)                               |
| Redmi 小爱触屏音箱 Pro 8 英寸 | [X08E](https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:speaker:0000A015:xiaomi-x08e:1) | `[7, 3]`   | `[7, 1]`      | -              | false          | [@shangjiyu](https://github.com/idootop/mi-gpt/issues/20)                              |

## ❌ 不支持

完全不支持 `MiGPT` 的小爱音箱型号有：

| 名称                   | 型号                                                           | 反馈来源                                                  |
| ---------------------- | -------------------------------------------------------------- | --------------------------------------------------------- |
| 小米小爱音箱 HD        | [SM4](https://home.miot-spec.com/spec/onemore.wifispeaker.sm4) | [@romantech](https://github.com/idootop/mi-gpt/issues/91) |
| 小米小爱蓝牙音箱随身版 | -                                                              | 微信: 明天                                                |

## 🔥 型号分享

如果你是其他型号的小爱音箱，欢迎把你的型号和配置参数分享给大家，分享格式如下：

- 名称：小爱音箱 Pro
- 型号：LX06
- ttsCommand：[5, 1]
- wakeUpCommand：[5, 3]
- playingCommand：未设置
- streamResponse：true（支持连续对话）

**Comment by gsscsd** [comment]
小爱mini可以的，刚测试成功

**Comment by idootop** [comment]
> 小爱mini可以的，刚测试成功

赞 👍 能分享下你的配置参数吗，我更新到上面的表格里。

**Comment by mingtian886** [comment]
> 小爱mini可以的，刚测试成功
名称：小爱音箱 Pro
型号：
ttsCommand：
wakeUpCommand：
playingCommand：
streamResponse：

能分享下嘛，我今天咸鱼下单了一个

**Comment by mingtian886** [comment]
小爱音箱 Play 型号：L05  
实测不支持
提示：
不到设备：小爱音箱Play
请检查你的设备名称是否正确，注意错别字、字母大小写和空格。
2024/06/14 13:55:56 Speaker ❌ 初始化 Mi Services 失败
2024/06/14 13:55:56 database ❌  Error: ❌ Assertion failed
    at _LoggerManager.assert (/app/dist/index.cjs:239:13)
    at __Logger.assert (/app/dist/index.cjs:276:19)
    at AISpeaker.initMiServices (/app/dist/index.cjs:451:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async AISpeaker.run (/app/dist/index.cjs:727:5)
    at async main (file:///app/app.js:6:3)

**Comment by mingtian886** [comment]
> 小爱mini可以的，刚测试成功

你的刷机了嘛，还是就是官方固件

**Comment by idootop** [comment]
@mingtian886 提示你了填写的设备名称有问题，找不到设备，去检查下和你米家里的名称是否一致。

如果名称没问题，可以打开 debug 看下你的输出日志，找到设备的真实 did 填上。

另外这个 issue 主要用来收集和分享小爱机型的配置参数。有新的问题直接带上设备型号和报错日志提新的 issue。

**Comment by wt666666** [comment]
- 名称：小爱音箱 Play (2019)
- 型号：LX05
- ttsCommand：[5, 1]
- wakeUpCommand：[5, 3]
- playingCommand：[3, 1 ,1]
- streamResponse：true（支持唤醒模式）

看情况，型号LX系列 应该会有较好的支持，似乎控制命令也都一样~
从2.0到3.1的使用体验，
关键词唤醒 连续对话，bot回答完，灯熄灭 再刚亮起的 时机，直接连续提问，识别及回答都比较完整流畅，
否则会出现识别不到 话听不全，出现bot说我再想想后，或卡住 或超时~~~可以再召唤一下，bot又把上一个问题i接着回答完~
- 退出关键词设了3个
    // 当消息以下面的关键词开头时，会退出 AI 唤醒状态
    exitKeywords: ["闭嘴", "退下", "再见"],
前两个关键词"闭嘴", "退下",一次都没成功退出过，且 说后会造成卡住，说"再见"也没用了。bot回答完，直接说"再见"可以退出~这一点儿太奇怪了~~~

**Comment by idootop** [comment]
“闭嘴”应该是触发了小爱音箱的“暂停播放”的操作，凡是涉及播放，暂停，调节音量这种音箱操作，小爱都不会记录到消息列表里，所以在外部收不到“闭嘴”这条消息指令，我猜“退下”应该也是同样的原因。

**Comment by idootop** [comment]
@mingtian886 找不到设备的问题，可以看下这里的 [FAQ](https://github.com/idootop/mi-gpt/blob/dev/docs/faq.md#q%E6%8F%90%E7%A4%BA%E6%89%BE%E4%B8%8D%E5%88%B0%E8%AE%BE%E5%A4%87xxx%E5%88%9D%E5%A7%8B%E5%8C%96-mi-services-%E5%A4%B1%E8%B4%A5)

**Comment by idootop** [comment]
@wx2020 之前有位老哥也是 LX04，好像没法正常连续对话。但理论上 LX 系列的机型应该都支持的

**Comment by smallfawn** [comment]
pro 官方不支持连续对话 对接mi-GPT就可以了吗

**Comment by idootop** [comment]
> pro 官方不支持连续对话 对接mi-GPT就可以了吗

能用，但效果不是很完美

**Comment by yitang823** [comment]
小爱音箱Art可以用吗?

**Comment by idootop** [comment]
> 小爱音箱Art可以用吗?

可以，不过貌似不支持连续对话

**Comment by YueYongDev** [comment]
小米sound可以吗

**Comment by idootop** [comment]
> 小米sound可以吗

@YueYongDev 看起来是支持的，连续对话需要试了才知道能不能用

**Comment by idootop** [comment]
@zwsn 感谢分享👍，已更新到上面的表格。

**Comment by ilovesouthpark** [comment]
名称：小爱触屏音箱
型号：LX04
ttsCommand：[5, 1]
wakeUpCommand：[5,2]
streamResponse：false 因为这个音箱本身也说出了音乐都不支持连续问答，所以好像不行，需要false否则判读句子读的状态错误读不完整。另外如果有时（我碰到了）名字修改后不能接入了，去debug里找MiotDID然后填入js里替代原来的DID。FAQ里有具体教程。

**Comment by idootop** [comment]
@ilovesouthpark 感谢分享，已更新到列表。

**Comment by pzhihao** [comment]
我的是小爱音箱PRO,为什么问问题没等我说完就开始回答呢？就听一半话就开始回答

**Comment by idootop** [comment]
> 就听一半话就开始回答

小爱音箱自身的限制，识别不了太长的消息指令，无解。

**Comment by IDarkBoss** [comment]
名称：小爱智能家庭屏10
型号：X10A
ttsCommand：[7, 3]
wakeUpCommand：[7, 1]
playingCommand：未设置
streamResponse：true（支持连续对话）

**Comment by idootop** [comment]
@IDarkBoss 已更新，感谢分享！

**Comment by yihong0618** [comment]
这个可以参考 xiaogpt 里面的代码基本都已经调研完了 command

**Comment by idootop** [comment]
@yihong0618 OK，稍后看下。后面写到代码里自动匹配确实更方便些。

**Comment by walterdreamlin** [comment]
> 名称：小爱智能家庭屏10 型号：X10A ttsCommand：[7, 3] wakeUpCommand：[7, 1] playingCommand：未设置 streamResponse：true（支持连续对话）

为何我的家庭屏10不支持连续对话？我看了，获取不到小爱是否在说话，用MINA或MIOT获取到的播放状态都是音乐是否播放的状态，不包括小爱说话，所以会被连续对话打断。

**Comment by lvxuan263** [comment]
Xiaomi 智能家庭屏 Pro 8 可以支持吗？

**Comment by idootop** [comment]
@lvxuan263 只要不是“❌ 不支持”列表里的，理论上都可以用。

**Comment by cxz19900127** [comment]
> 名称：小爱智能家庭屏10
> 
> 型号：X10A
> 
> ttsCommand：[7, 3]
> 
> wakeUpCommand：[7, 1]
> 
> playingCommand：未设置
> 
> streamResponse：true（支持连续对话）

我也是家庭屏10，为啥我之前按这个设置不行呢？可以连续对话，但是回答问题说一半就打断了。大神求解啊

**Comment by idootop** [comment]
@cxz19900127 那就说明这个型号（X10A）不支持连续对话模式，建议关闭 streamResponse。

**Comment by colynxu** [comment]
名称：Redmi小爱音箱 Play

型号：L07A

ttsCommand：[5, 1]

wakeUpCommand：[5, 2]

playingCommand：未设置

streamResponse：true（支持连续对话）

**Comment by anseirai** [comment]
> 名称：Redmi小爱音箱 Play
> 
> 型号：L07A
> 
> ttsCommand：[5, 1]
> 
> wakeUpCommand：[5, 2]
> 
> playingCommand：未设置
> 
> streamResponse：true（支持连续对话）

型号貌似是：L7A 没有零
另外playingCommand: [4, 1, 1]貌似也能work

**Comment by PaPerseller** [comment]
> 名称：Redmi小爱音箱 Play
> 
> 型号：L07A
> 
> ttsCommand：[5, 1]
> 
> wakeUpCommand：[5, 2]
> 
> playingCommand：未设置
> 
> streamResponse：true（支持连续对话）

已验证可用，型号为 L07A

**Comment by imcaptor** [comment]
名称：Redmi小爱触屏音箱8
型号：X08C
ttsCommand：[3, 1]
wakeUpCommand：[3, 2]
playingCommand：未设置
streamResponse：false

不知道是不是支持联系对话，既然pro都不支持，估计这个也不支持吧。

**Comment by m8458246** [comment]
有人试过小爱音箱art 电池板支持不，型号：L09B

**Comment by liangdk0809** [comment]
小爱音响pro
感觉没联网有点智障啊
Speaker 🔥 黄帝内经中的五谷是指哪五谷
 Speaker 🔊 请稍等
 Open AI ✅ Answer: 哎呀，小千主人，我也不太清楚呢，要不咱们一起查查？
 Speaker 🔊 哎呀，小千主人，我也不太清楚呢，要不咱们一起查查？
用的豆包模型，问的就是不清楚，大模型上问没问题

**Comment by arronwy** [comment]
我是`Xiaomi 智能家庭屏 6`， 发现不支持 streamResponse，播放一半中断，但看 playState 状态是 pause，配置 `playingCommand: [3, 1, 1],` 也无效，但是规格上显示支持的，大家有建议吗？

![image](https://github.com/user-attachments/assets/295a5b65-5f7a-4a8b-9a8e-95ff2a862867)

```
2024/07/28 11:08:43 Speaker 🔊 让我先想想
2024/07/28 11:08:46 Speaker 🐛 {"playState":2}
2024/07/28 11:08:47 Open AI ✅ Answer: 主人，我在呢！今天有什么好玩的事情要和我分享吗？
2024/07/28 11:08:48 Speaker 🔊 主人，我在呢！今天有什么好玩的事情要和我分享吗？
2024/07/28 11:08:52 Speaker 🐛 {"playState":2}
2024/07/28 11:08:52 Speaker 🔊 还有其他问题吗
2024/07/28 11:08:55 Speaker 🐛 {"playState":2}
```

**Comment by fjmscut** [comment]
请问支持小米智能面板吗？

**Comment by AlongLin** [comment]
刚测试成功！

名称：[Xiaomi 智能家庭屏 Pro 8]
型号：
ttsCommand：·7, 3
wakeUpCommand：7,1
playingCommand：3,1,1 ## 未启用
streamResponse：false  ## 打开后，可以使用，但是会导致回答被中断，非常影响使用效果，故选择关闭

使用过程中，出现的问题。
安装方法docker
(1) did是一串数字，通过调试模式，找到的，使用中文一直找不到设备，最后发现是一串数字；
(2) 无法登陆，发现是网络问题，默认是bridge，改成host，就可以登陆小米服务了。

感谢佬的工作！大大的赞！祝佬早日百万年薪！

**Comment by Kente-Z** [comment]
> 刚测试成功！
> 
> 名称：[Xiaomi 智能家庭屏 Pro 8] 型号： ttsCommand：7, 3 wakeUpCommand：7,1 playingCommand：3,1,1 ## 未启用 streamResponse：false ## 打开后，可以使用，但是会导致回答被中断，非常影响使用效果，故选择关闭
> 
> 安装方法docker，部署在内网服务器(ubuntu 22.04)。
> 
> 使用过程中，出现的问题。
> 
> (1) did是一串数字，通过调试模式，找到的，使用中文一直找不到设备，最后发现是一串数字； (2) 无法登陆，发现是网络问题，默认是bridge，改成host，就可以登陆小米服务了； (3) 使用过程中，又再次出现无法登陆小米服务器的情况，考虑还是网络的问题，把科学代理（v2rayA）关了就又行了。
> 
> 感谢佬的工作！大大的赞！祝佬早日百万年薪！

同样的小米智能家庭屏Pro 8，我docker命令行里没问题 没报错，也能正常返回信息，但是音箱不会播报，没有声音，设置的没问题

**Comment by AlongLin** [comment]
> > 刚测试成功！
> > 名称：[Xiaomi 智能家庭屏 Pro 8] 型号： ttsCommand：7, 3 wakeUpCommand：7,1 playingCommand：3,1,1 ## 未启用 streamResponse：false ## 打开后，可以使用，但是会导致回答被中断，非常影响使用效果，故选择关闭
> > 安装方法docker，部署在内网服务器(ubuntu 22.04)。
> > 使用过程中，出现的问题。
> > (1) did是一串数字，通过调试模式，找到的，使用中文一直找不到设备，最后发现是一串数字； (2) 无法登陆，发现是网络问题，默认是bridge，改成host，就可以登陆小米服务了； (3) 使用过程中，又再次出现无法登陆小米服务器的情况，考虑还是网络的问题，把科学代理（v2rayA）关了就又行了。
> > 感谢佬的工作！大大的赞！祝佬早日百万年薪！
> 
> 同样的小米智能家庭屏Pro 8，我docker命令行里没问题 没报错，也能正常返回信息，但是音箱不会播报，没有声音，设置的没问题

docker ps 看一下镜像是否正常运行？ 然后查查log有没有报错？我这台机器除了偶尔后台会自动停止运行，很稳定。

**Comment by haihaigege184** [comment]
傻妞回答之前小爱回答的那两字真坏体验啊，没有高手出奇招么？

**Comment by CK-LIN** [comment]
LX01
小爱mini
用的是doubao的接口
设置了连续对话，但是关键词无效
![image](https://github.com/user-attachments/assets/984338f9-cd29-48fc-b388-01cf62c61f28)
![image](https://github.com/user-attachments/assets/fd8cf789-99d7-4533-9ff1-09e750967b79)

是设备原因还是AI的原因？

**Comment by shanelau** [comment]
Xiaomi智能家庭屏Mini 这个支持吗？有没有测试成功的？

**Comment by haoxian2023** [comment]
> 小米sound可以吗

按照spec上的ttscommand和wakeupcommand的数值配置了，还是没生效。

**Comment by VincentGresham** [comment]
名称 | 型号 | ttsCommand | wakeUpCommand | playingCommand | streamResponse | 反馈来源
-- | -- | -- | -- | -- | -- | --
Xiaomi智能家庭屏Mini | [ASX4B](https://home.miot-spec.com/spec/xiaomi.wifispeaker.x4b) | [5, 3] | [5, 1] | [3, 1, 1] | true | @VincentGresham

**Comment by VincentGresham** [comment]
> Xiaomi智能家庭屏Mini 这个支持吗？有没有测试成功的？

可行,配置已贴

**Comment by idootop** [comment]
> 名称 	型号 	ttsCommand 	wakeUpCommand 	playingCommand 	streamResponse 	反馈来源
> Xiaomi智能家庭屏Mini 	[ASX4B](https://home.miot-spec.com/spec/xiaomi.wifispeaker.x4b) 	[5, 3] 	[5, 1] 	[3, 1, 1] 	true 	[@VincentGresham](https://github.com/VincentGresham)

@VincentGresham 多谢反馈，已更新

**Comment by lenetzp** [comment]
小爱智能闹钟可以吗？

**Comment by LeoWang1991** [comment]
借楼问一下小爱同学儿童版 能支持么？

**Comment by mascc** [comment]
小爱音箱 mini | LX01  目前测试并不能支持连续对话。加不加播放状态检测都不太行，有其他人用 这款 测试连续对话成功了么？

**Comment by idootop** [comment]
@wangwy1015 刚试了下，最新发布的小爱音箱 Pro 也可以用的，配置参数已经更新在上面表格里了。

**Comment by wangwy1015** [comment]
> [@wangwy1015](https://github.com/wangwy1015) 刚试了下，最新发布的小爱音箱 Pro 也可以用的，配置参数已经更新在上面表格里了。

感谢！

**Comment by idootop** [comment]
@hongyun-robot 如果设备列表里没有展示出来对应的设备，那就是不支持

**Comment by shepherdwind** [comment]
我试了下我的儿童音响，可以正常对话，但是音响的答复并不是终端的结果，这个是哪里配置不对么？

是 ttsCommand 不对吗？但是我从那个网站找不到我的产品，有其他办法吗？

<img width="963" alt="Image" src="https://github.com/user-attachments/assets/d66c7750-d674-4c0e-a8f1-c0ed90e2f6b4" />

**Comment by idootop** [comment]
@shepherdwind 那就是不支持你这个型号

**Comment by igaojie** [comment]
名称：Xiaomi Sound
型号：L16A
ttsCommand：[7, 3]
wakeUpCommand：[7, 1]
playingCommand：未设置
streamResponse：true（支持连续对话） 刚测试通过。

**Comment by bloodgcat** [comment]
Redmi 小爱触屏音箱 8不支持

**Comment by grissomsh** [comment]
Xiaomi 智能音箱 Pro
已经按照要求设置：

```text
    ttsCommand: [7, 3],
    // 设备唤醒指令，请到 https://home.miot-spec.com 查询具体指令
    wakeUpCommand: [7, 1],
```

可以换出，说了第一句话“你好，我是傻妞，很高兴认识你”（可以听到语音），但是后面就会有如下信息：

```text
2025/03/30 08:33:26 Speaker 🐛 设备信息： {
    "name": "Xiaomi 智能音箱 Pro",
    "desc": "设备在线 ",
    "model": "xiaomi.wifispeaker.oh2p",
    "rom": "1.56.16"
}
2025/03/30 08:33:26 Speaker ✅ 服务已启动...
2025/03/30 08:34:33 Speaker 🔥 召唤傻妞
2025/03/30 08:34:33 Speaker 🔊 你好，我是傻妞，很高兴认识你
2025/03/30 08:34:37 Speaker 🐛 {"playState":{"status":"playing","volume":28,"loop_type":1}}
2025/03/30 08:34:38 Speaker 🐛 {"playState":{"status":"playing","volume":28,"loop_type":1,"media_type":3,"play_song_detail":{"audio_id":"2879544480427409506","position":222681,"duration":234893},"track_list":["2879544480427409506","842068729326994024"]}}
2025/03/30 08:35:08 Speaker 🔊 傻妞已退出
2025/03/30 08:35:14 Speaker 🐛 {"playState":"undefined"}
❌ _callMina failed {
  code: 101,
  message: 'ubus server or device returned invalid result',
  data: {
    device_data: '{"msg":"远程控制超时","code":3012}',
    reqID: '9bcc7a00-a6cd-4589-a9cf-9c3f3b52759a'
  }
}
2025/03/30 08:35:14 Speaker ❌ 获取设备状态失败，正在重试: 1
❌ _callMina failed {
  code: 101,
  message: 'ubus server or device returned invalid result',
  data: {
    device_data: '{"msg":"远程控制超时","code":3012}',
    reqID: 'ea4a7473-65b1-4529-acc2-33651964962d'
  }
}
2025/03/30 08:35:18 Speaker ❌ 获取设备状态失败，正在重试: 2
2025/03/30 08:35:18 Speaker 🐛 {"playState":"undefined"}
2025/03/30 08:35:21 Speaker 🐛 {"playState":"undefined"}
❌ _callMina failed {
  code: 101,
  message: 'ubus server or device returned invalid result',
  data: {
    device_data: '{"msg":"远程控制超时","code":3012}',
    reqID: '9328e425-c890-4bb6-b7ea-57afa4405b06'
  }
}
2025/03/30 08:35:21 Speaker ❌ 获取设备状态失败，正在重试: 3
2025/03/30 08:35:23 Speaker 🔥 看演唱
2025/03/30 08:35:25 Speaker 🐛 {"playState":"undefined"}
❌ _callMina failed {
  code: 101,
  message: 'ubus server or device returned invalid result',
  data: {
    device_data: '{"msg":"远程控制超时","code":3012}',
    reqID: '2242b3d1-e87e-41af-bf09-30c39a3ca549'
  }
}
2025/03/30 08:35:25 Speaker 🐛 unWakeUp
❌ _callMina failed {
  code: 101,
  message: 'ubus server or device returned invalid result',
  data: {
    device_data: '{"msg":"远程控制超时","code":3012}',
    reqID: 'da684487-a6d7-4359-8668-6fd9be624072'
  }
}
```

请问可能是什么原因？

**Comment by blueskyxxz** [comment]
名称：小爱音箱 mini
型号：[LX01]
ttsCommand：[5, 1]
wakeUpCommand：[5, 2]
playingCommand：[4,1,1]
streamResponse：true（支持连续对话）

**Comment by idootop** [comment]
全套的小爱音箱刷机教程和解决方案已发布，详情请移步至：https://github.com/idootop/mi-gpt/issues/322

**Comment by MXXBXX-1** [comment]
名称：Redmi小爱音箱 Play
型号：L07A
ttsCommand：[5, 1]
wakeUpCommand：[5, 2]
playingCommand：未设置
streamResponse：flase（不支持连续对话）

**Comment by 115458440sf** [comment]
我一个pro，3个play增强版，难道要拉3个docker？

**Comment by cairongquan** [comment]
登录不上的修改node_modules的源码，[参考这个项目的issus](https://github.com/Yonsm/MiService/issues/56)
